"""
D&D 5e spell lists by class and level (PHB core spells).
Each entry: (name, school, ritual, concentration)
"""

CANTRIPS = {
    "Artificer": [
        ("Acid Splash","Conjuration",False,False),("Fire Bolt","Evocation",False,False),
        ("Guidance","Divination",False,True),("Light","Evocation",False,False),
        ("Mage Hand","Conjuration",False,False),("Mending","Transmutation",False,False),
        ("Message","Transmutation",False,False),("Poison Spray","Conjuration",False,False),
        ("Prestidigitation","Transmutation",False,False),("Ray of Frost","Evocation",False,False),
        ("Resistance","Abjuration",False,True),("Shocking Grasp","Evocation",False,False),
        ("Spare the Dying","Necromancy",False,False),("Thorn Whip","Transmutation",False,False),
        ("Thunderclap","Evocation",False,False),
    ],
    "Bard": [
        ("Blade Ward","Abjuration",False,False),("Dancing Lights","Evocation",False,True),
        ("Friends","Enchantment",False,True),("Light","Evocation",False,False),
        ("Mage Hand","Conjuration",False,False),("Mending","Transmutation",False,False),
        ("Message","Transmutation",False,False),("Minor Illusion","Illusion",False,False),
        ("Prestidigitation","Transmutation",False,False),("Thunderclap","Evocation",False,False),
        ("True Strike","Divination",False,True),("Vicious Mockery","Enchantment",False,False),
    ],
    "Cleric": [
        ("Guidance","Divination",False,True),("Light","Evocation",False,False),
        ("Mending","Transmutation",False,False),("Resistance","Abjuration",False,True),
        ("Sacred Flame","Evocation",False,False),("Spare the Dying","Necromancy",False,False),
        ("Thaumaturgy","Transmutation",False,False),("Toll the Dead","Necromancy",False,False),
        ("Word of Radiance","Evocation",False,False),
    ],
    "Druid": [
        ("Druidcraft","Transmutation",False,False),("Guidance","Divination",False,True),
        ("Infestation","Conjuration",False,False),("Mending","Transmutation",False,False),
        ("Poison Spray","Conjuration",False,False),("Produce Flame","Conjuration",False,False),
        ("Resistance","Abjuration",False,True),("Shillelagh","Transmutation",False,True),
        ("Thorn Whip","Transmutation",False,False),("Thunderclap","Evocation",False,False),
    ],
    "Sorcerer": [
        ("Acid Splash","Conjuration",False,False),("Blade Ward","Abjuration",False,False),
        ("Chill Touch","Necromancy",False,False),("Dancing Lights","Evocation",False,True),
        ("Fire Bolt","Evocation",False,False),("Friends","Enchantment",False,True),
        ("Light","Evocation",False,False),("Mage Hand","Conjuration",False,False),
        ("Mending","Transmutation",False,False),("Message","Transmutation",False,False),
        ("Minor Illusion","Illusion",False,False),("Poison Spray","Conjuration",False,False),
        ("Prestidigitation","Transmutation",False,False),("Ray of Frost","Evocation",False,False),
        ("Shocking Grasp","Evocation",False,False),("Thunderclap","Evocation",False,False),
        ("True Strike","Divination",False,True),
    ],
    "Warlock": [
        ("Blade Ward","Abjuration",False,False),("Chill Touch","Necromancy",False,False),
        ("Eldritch Blast","Evocation",False,False),("Friends","Enchantment",False,True),
        ("Mage Hand","Conjuration",False,False),("Minor Illusion","Illusion",False,False),
        ("Poison Spray","Conjuration",False,False),("Prestidigitation","Transmutation",False,False),
        ("True Strike","Divination",False,True),
    ],
    "Wizard": [
        ("Acid Splash","Conjuration",False,False),("Blade Ward","Abjuration",False,False),
        ("Chill Touch","Necromancy",False,False),("Dancing Lights","Evocation",False,True),
        ("Fire Bolt","Evocation",False,False),("Friends","Enchantment",False,True),
        ("Light","Evocation",False,False),("Mage Hand","Conjuration",False,False),
        ("Mending","Transmutation",False,False),("Message","Transmutation",False,False),
        ("Minor Illusion","Illusion",False,False),("Poison Spray","Conjuration",False,False),
        ("Prestidigitation","Transmutation",False,False),("Ray of Frost","Evocation",False,False),
        ("Shocking Grasp","Evocation",False,False),("Thunderclap","Evocation",False,False),
        ("True Strike","Divination",False,True),
    ],
}

# Leveled spells by class: {class: {level: [(name, school, ritual, concentration), ...]}}
SPELLS = {
    "Artificer": {
        1: [("Absorb Elements","Abjuration",False,False),("Alarm","Abjuration",True,False),
            ("Catapult","Transmutation",False,False),("Cure Wounds","Evocation",False,False),
            ("Detect Magic","Divination",True,True),("Disguise Self","Illusion",False,False),
            ("Expeditious Retreat","Transmutation",False,True),("Faerie Fire","Evocation",False,True),
            ("False Life","Necromancy",False,False),("Feather Fall","Transmutation",False,False),
            ("Grease","Conjuration",False,False),("Identify","Divination",True,False),
            ("Jump","Transmutation",False,False),("Longstrider","Transmutation",False,False),
            ("Purify Food and Drink","Transmutation",True,False),("Sanctuary","Abjuration",False,False),
            ("Shield of Faith","Abjuration",False,True),],
        2: [("Aid","Abjuration",False,False),("Arcane Lock","Abjuration",False,False),
            ("Blur","Illusion",False,True),("Continual Flame","Evocation",False,False),
            ("Darkvision","Transmutation",False,False),("Enhance Ability","Transmutation",False,True),
            ("Enlarge/Reduce","Transmutation",False,True),("Heat Metal","Transmutation",False,True),
            ("Invisibility","Illusion",False,True),("Lesser Restoration","Abjuration",False,False),
            ("Levitate","Transmutation",False,True),("Magic Mouth","Illusion",True,False),
            ("Magic Weapon","Transmutation",False,True),("Protection from Poison","Abjuration",False,False),
            ("Rope Trick","Transmutation",False,False),("See Invisibility","Divination",False,False),
            ("Skywrite","Transmutation",True,True),("Spider Climb","Transmutation",False,True),
            ("Web","Conjuration",False,True),],
        3: [("Blink","Transmutation",False,False),("Catnap","Enchantment",False,False),
            ("Create Food and Water","Conjuration",False,False),("Dispel Magic","Abjuration",False,False),
            ("Elemental Weapon","Transmutation",False,True),("Fly","Transmutation",False,True),
            ("Glyph of Warding","Abjuration",False,False),("Haste","Transmutation",False,True),
            ("Intellect Fortress","Abjuration",False,True),("Magic Circle","Abjuration",False,False),
            ("Mass Healing Word","Evocation",False,False),("Meld into Stone","Transmutation",True,False),
            ("Protection from Energy","Abjuration",False,True),("Revivify","Necromancy",False,False),
            ("Tiny Servant","Transmutation",False,False),("Water Breathing","Transmutation",True,False),
            ("Water Walk","Transmutation",True,False),],
        4: [("Arcane Eye","Divination",False,True),("Elemental Bane","Transmutation",False,True),
            ("Fabricate","Transmutation",False,False),("Freedom of Movement","Abjuration",False,False),
            ("Leomund's Secret Chest","Conjuration",False,False),("Mordenkainen's Faithful Hound","Conjuration",False,False),
            ("Mordenkainen's Private Sanctum","Abjuration",False,False),("Otiluke's Resilient Sphere","Evocation",False,True),
            ("Stone Shape","Transmutation",False,False),("Stoneskin","Abjuration",False,True),],
        5: [("Animate Objects","Transmutation",False,True),("Bigby's Hand","Evocation",False,True),
            ("Creation","Illusion",False,False),("Greater Restoration","Abjuration",False,False),
            ("Skill Empowerment","Transmutation",False,True),("Transmute Rock","Transmutation",False,False),
            ("Wall of Stone","Evocation",False,True),],
    },
    "Bard": {
        1: [("Animal Friendship","Enchantment",False,False),("Bane","Enchantment",False,True),
            ("Charm Person","Enchantment",False,False),("Color Spray","Illusion",False,False),
            ("Command","Enchantment",False,False),("Comprehend Languages","Divination",True,False),
            ("Cure Wounds","Evocation",False,False),("Detect Magic","Divination",True,True),
            ("Disguise Self","Illusion",False,False),("Dissonant Whispers","Enchantment",False,False),
            ("Earth Tremor","Evocation",False,False),("Faerie Fire","Evocation",False,True),
            ("Feather Fall","Transmutation",False,False),("Healing Word","Evocation",False,False),
            ("Heroism","Enchantment",False,True),("Identify","Divination",True,False),
            ("Illusory Script","Illusion",True,False),("Longstrider","Transmutation",False,False),
            ("Silent Image","Illusion",False,True),("Sleep","Enchantment",False,False),
            ("Speak with Animals","Divination",True,False),("Thunderwave","Evocation",False,False),
            ("Unseen Servant","Conjuration",True,False),],
        2: [("Animal Messenger","Enchantment",True,False),("Blindness/Deafness","Necromancy",False,False),
            ("Calm Emotions","Enchantment",False,True),("Cloud of Daggers","Conjuration",False,True),
            ("Crown of Madness","Enchantment",False,True),("Detect Thoughts","Divination",False,True),
            ("Enhance Ability","Transmutation",False,True),("Enthrall","Enchantment",False,True),
            ("Heat Metal","Transmutation",False,True),("Hold Person","Enchantment",False,True),
            ("Invisibility","Illusion",False,True),("Knock","Transmutation",False,False),
            ("Lesser Restoration","Abjuration",False,False),("Locate Animals or Plants","Divination",True,False),
            ("Locate Object","Divination",False,True),("Magic Mouth","Illusion",True,False),
            ("Phantasmal Force","Illusion",False,True),("See Invisibility","Divination",False,False),
            ("Shatter","Evocation",False,False),("Silence","Illusion",True,True),
            ("Suggestion","Enchantment",False,True),("Zone of Truth","Enchantment",False,False),],
        3: [("Bestow Curse","Necromancy",False,True),("Clairvoyance","Divination",False,True),
            ("Dispel Magic","Abjuration",False,False),("Fear","Illusion",False,True),
            ("Feign Death","Necromancy",True,False),("Glyph of Warding","Abjuration",False,False),
            ("Hypnotic Pattern","Illusion",False,True),("Leomund's Tiny Hut","Evocation",True,False),
            ("Major Image","Illusion",False,True),("Mass Healing Word","Evocation",False,False),
            ("Nondetection","Abjuration",False,False),("Plant Growth","Transmutation",False,False),
            ("Sending","Evocation",False,False),("Speak with Dead","Necromancy",False,False),
            ("Speak with Plants","Transmutation",False,False),("Stinking Cloud","Conjuration",False,True),
            ("Tongues","Divination",False,False),],
        4: [("Compulsion","Enchantment",False,True),("Confusion","Enchantment",False,True),
            ("Dimension Door","Conjuration",False,False),("Freedom of Movement","Abjuration",False,False),
            ("Greater Invisibility","Illusion",False,True),("Hallucinatory Terrain","Illusion",False,False),
            ("Locate Creature","Divination",False,True),("Phantasmal Killer","Illusion",False,True),
            ("Polymorph","Transmutation",False,True),],
        5: [("Animate Objects","Transmutation",False,True),("Awaken","Transmutation",False,False),
            ("Dominate Person","Enchantment",False,True),("Dream","Illusion",False,False),
            ("Geas","Enchantment",False,False),("Greater Restoration","Abjuration",False,False),
            ("Hold Monster","Enchantment",False,True),("Legend Lore","Divination",False,False),
            ("Mass Cure Wounds","Evocation",False,False),("Mislead","Illusion",False,True),
            ("Modify Memory","Enchantment",False,True),("Planar Binding","Abjuration",False,False),
            ("Raise Dead","Necromancy",False,False),("Scrying","Divination",False,True),
            ("Seeming","Illusion",False,False),("Teleportation Circle","Conjuration",False,False),],
        6: [("Eyebite","Necromancy",False,True),("Find the Path","Divination",False,True),
            ("Guards and Wards","Abjuration",False,False),("Mass Suggestion","Enchantment",False,False),
            ("Otto's Irresistible Dance","Enchantment",False,True),("Programmed Illusion","Illusion",False,False),
            ("True Seeing","Divination",False,False),],
        7: [("Etherealness","Transmutation",False,False),("Forcecage","Evocation",False,False),
            ("Mirage Arcane","Illusion",False,False),("Mordenkainen's Magnificent Mansion","Conjuration",False,False),
            ("Mordenkainen's Sword","Evocation",False,True),("Project Image","Illusion",False,True),
            ("Regenerate","Transmutation",False,False),("Resurrection","Necromancy",False,False),
            ("Symbol","Abjuration",False,False),("Teleport","Conjuration",False,False),],
        8: [("Dominate Monster","Enchantment",False,True),("Feeblemind","Enchantment",False,False),
            ("Glibness","Transmutation",False,False),("Mind Blank","Abjuration",False,False),
            ("Power Word Stun","Enchantment",False,False),],
        9: [("Foresight","Divination",False,False),("Power Word Heal","Evocation",False,False),
            ("Power Word Kill","Enchantment",False,False),("True Polymorph","Transmutation",False,True),],
    },
    "Cleric": {
        1: [("Bane","Enchantment",False,True),("Bless","Enchantment",False,True),
            ("Ceremony","Abjuration",True,False),("Command","Enchantment",False,False),
            ("Create or Destroy Water","Transmutation",False,False),("Cure Wounds","Evocation",False,False),
            ("Detect Evil and Good","Divination",False,True),("Detect Magic","Divination",True,True),
            ("Detect Poison and Disease","Divination",True,True),("Guiding Bolt","Evocation",False,False),
            ("Healing Word","Evocation",False,False),("Inflict Wounds","Necromancy",False,False),
            ("Protection from Evil and Good","Abjuration",False,True),("Purify Food and Drink","Transmutation",True,False),
            ("Sanctuary","Abjuration",False,False),("Shield of Faith","Abjuration",False,True),],
        2: [("Aid","Abjuration",False,False),("Augury","Divination",True,False),
            ("Blindness/Deafness","Necromancy",False,False),("Calm Emotions","Enchantment",False,True),
            ("Continual Flame","Evocation",False,False),("Enhance Ability","Transmutation",False,True),
            ("Find Traps","Divination",False,False),("Gentle Repose","Necromancy",True,False),
            ("Hold Person","Enchantment",False,True),("Lesser Restoration","Abjuration",False,False),
            ("Locate Object","Divination",False,True),("Prayer of Healing","Evocation",False,False),
            ("Protection from Poison","Abjuration",False,False),("Silence","Illusion",True,True),
            ("Spiritual Weapon","Evocation",False,False),("Warding Bond","Abjuration",False,False),
            ("Zone of Truth","Enchantment",False,False),],
        3: [("Animate Dead","Necromancy",False,False),("Bestow Curse","Necromancy",False,True),
            ("Clairvoyance","Divination",False,True),("Create Food and Water","Conjuration",False,False),
            ("Daylight","Evocation",False,False),("Dispel Magic","Abjuration",False,False),
            ("Feign Death","Necromancy",True,False),("Glyph of Warding","Abjuration",False,False),
            ("Magic Circle","Abjuration",False,False),("Mass Healing Word","Evocation",False,False),
            ("Meld into Stone","Transmutation",True,False),("Protection from Energy","Abjuration",False,True),
            ("Remove Curse","Abjuration",False,False),("Revivify","Necromancy",False,False),
            ("Sending","Evocation",False,False),("Speak with Dead","Necromancy",False,False),
            ("Spirit Guardians","Conjuration",False,True),("Tongues","Divination",False,False),
            ("Water Walk","Transmutation",True,False),("Wind Wall","Evocation",False,True),],
        4: [("Banishment","Abjuration",False,True),("Control Water","Transmutation",False,True),
            ("Death Ward","Abjuration",False,False),("Divination","Divination",True,False),
            ("Freedom of Movement","Abjuration",False,False),("Guardian of Faith","Conjuration",False,False),
            ("Locate Creature","Divination",False,True),("Stone Shape","Transmutation",False,False),],
        5: [("Commune","Divination",True,False),("Contagion","Necromancy",False,False),
            ("Dispel Evil and Good","Abjuration",False,True),("Flame Strike","Evocation",False,False),
            ("Geas","Enchantment",False,False),("Greater Restoration","Abjuration",False,False),
            ("Hallow","Evocation",False,False),("Hold Monster","Enchantment",False,True),
            ("Legend Lore","Divination",False,False),("Mass Cure Wounds","Evocation",False,False),
            ("Planar Binding","Abjuration",False,False),("Raise Dead","Necromancy",False,False),
            ("Scrying","Divination",False,True),("Summon Celestial","Conjuration",False,True),],
        6: [("Blade Barrier","Evocation",False,True),("Create Undead","Necromancy",False,False),
            ("Find the Path","Divination",False,True),("Forbiddance","Abjuration",True,False),
            ("Harm","Necromancy",False,False),("Heal","Evocation",False,False),
            ("Heroes' Feast","Conjuration",False,False),("Planar Ally","Conjuration",False,False),
            ("True Seeing","Divination",False,False),("Word of Recall","Conjuration",False,False),],
        7: [("Conjure Celestial","Conjuration",False,True),("Divine Word","Evocation",False,False),
            ("Etherealness","Transmutation",False,False),("Fire Storm","Evocation",False,False),
            ("Plane Shift","Conjuration",False,False),("Regenerate","Transmutation",False,False),
            ("Resurrection","Necromancy",False,False),("Symbol","Abjuration",False,False),
            ("Temple of the Gods","Conjuration",False,False),],
        8: [("Antimagic Field","Abjuration",False,True),("Control Weather","Transmutation",False,True),
            ("Earthquake","Evocation",False,True),("Holy Aura","Abjuration",False,True),],
        9: [("Astral Projection","Necromancy",False,False),("Gate","Conjuration",False,True),
            ("Mass Heal","Evocation",False,False),("True Resurrection","Necromancy",False,False),],
    },
    "Druid": {
        1: [("Animal Friendship","Enchantment",False,False),("Charm Person","Enchantment",False,False),
            ("Create or Destroy Water","Transmutation",False,False),("Cure Wounds","Evocation",False,False),
            ("Detect Magic","Divination",True,True),("Detect Poison and Disease","Divination",True,True),
            ("Entangle","Conjuration",False,True),("Faerie Fire","Evocation",False,True),
            ("Fog Cloud","Conjuration",False,True),("Goodberry","Transmutation",False,False),
            ("Healing Word","Evocation",False,False),("Ice Knife","Conjuration",False,False),
            ("Jump","Transmutation",False,False),("Longstrider","Transmutation",False,False),
            ("Purify Food and Drink","Transmutation",True,False),("Speak with Animals","Divination",True,False),
            ("Thunderwave","Evocation",False,False),],
        2: [("Animal Messenger","Enchantment",True,False),("Barkskin","Transmutation",False,True),
            ("Beast Sense","Divination",True,True),("Darkvision","Transmutation",False,False),
            ("Earthbind","Transmutation",False,True),("Enhance Ability","Transmutation",False,True),
            ("Find Traps","Divination",False,False),("Flame Blade","Evocation",False,True),
            ("Flaming Sphere","Conjuration",False,True),("Gust of Wind","Evocation",False,True),
            ("Heat Metal","Transmutation",False,True),("Hold Person","Enchantment",False,True),
            ("Lesser Restoration","Abjuration",False,False),("Locate Animals or Plants","Divination",True,False),
            ("Locate Object","Divination",False,True),("Moonbeam","Evocation",False,True),
            ("Pass without Trace","Abjuration",False,True),("Protection from Poison","Abjuration",False,False),
            ("Spike Growth","Transmutation",False,True),("Warding Wind","Evocation",False,True),],
        3: [("Call Lightning","Conjuration",False,True),("Conjure Animals","Conjuration",False,True),
            ("Daylight","Evocation",False,False),("Dispel Magic","Abjuration",False,False),
            ("Erupting Earth","Transmutation",False,False),("Feign Death","Necromancy",True,False),
            ("Meld into Stone","Transmutation",True,False),("Plant Growth","Transmutation",False,False),
            ("Protection from Energy","Abjuration",False,True),("Sleet Storm","Conjuration",False,True),
            ("Speak with Plants","Transmutation",False,False),("Tidal Wave","Conjuration",False,False),
            ("Wall of Water","Evocation",False,True),("Water Breathing","Transmutation",True,False),
            ("Water Walk","Transmutation",True,False),("Wind Wall","Evocation",False,True),],
        4: [("Blight","Necromancy",False,False),("Confusion","Enchantment",False,True),
            ("Conjure Minor Elementals","Conjuration",False,True),("Conjure Woodland Beings","Conjuration",False,True),
            ("Control Water","Transmutation",False,True),("Dominate Beast","Enchantment",False,True),
            ("Freedom of Movement","Abjuration",False,False),("Giant Insect","Transmutation",False,True),
            ("Grasping Vine","Conjuration",False,True),("Hallucinatory Terrain","Illusion",False,False),
            ("Ice Storm","Evocation",False,False),("Locate Creature","Divination",False,True),
            ("Polymorph","Transmutation",False,True),("Stone Shape","Transmutation",False,False),
            ("Stoneskin","Abjuration",False,True),("Watery Sphere","Conjuration",False,True),],
        5: [("Antilife Shell","Abjuration",False,True),("Awaken","Transmutation",False,False),
            ("Commune with Nature","Divination",True,False),("Cone of Cold","Evocation",False,False),
            ("Conjure Elemental","Conjuration",False,True),("Contagion","Necromancy",False,False),
            ("Control Winds","Transmutation",False,True),("Geas","Enchantment",False,False),
            ("Greater Restoration","Abjuration",False,False),("Insect Plague","Conjuration",False,True),
            ("Maelstrom","Evocation",False,True),("Mass Cure Wounds","Evocation",False,False),
            ("Planar Binding","Abjuration",False,False),("Reincarnate","Transmutation",False,False),
            ("Scrying","Divination",False,True),("Transmute Rock","Transmutation",False,False),
            ("Tree Stride","Conjuration",False,True),("Wall of Stone","Evocation",False,True),],
        6: [("Conjure Fey","Conjuration",False,True),("Find the Path","Divination",False,True),
            ("Flesh to Stone","Transmutation",False,True),("Heal","Evocation",False,False),
            ("Heroes' Feast","Conjuration",False,False),("Move Earth","Transmutation",False,True),
            ("Primordial Ward","Abjuration",False,True),("Sunbeam","Evocation",False,True),
            ("Transport via Plants","Conjuration",False,False),("Wall of Thorns","Conjuration",False,True),
            ("Wind Walk","Transmutation",False,False),],
        7: [("Fire Storm","Evocation",False,False),("Mirage Arcane","Illusion",False,False),
            ("Plane Shift","Conjuration",False,False),("Regenerate","Transmutation",False,False),
            ("Reverse Gravity","Transmutation",False,True),("Symbol","Abjuration",False,False),
            ("Whirlwind","Evocation",False,True),],
        8: [("Animal Shapes","Transmutation",False,True),("Antipathy/Sympathy","Enchantment",False,False),
            ("Control Weather","Transmutation",False,True),("Earthquake","Evocation",False,True),
            ("Feeblemind","Enchantment",False,False),("Sunburst","Evocation",False,False),
            ("Tsunami","Conjuration",False,True),],
        9: [("Foresight","Divination",False,False),("Shapechange","Transmutation",False,True),
            ("Storm of Vengeance","Conjuration",False,True),("True Resurrection","Necromancy",False,False),],
    },
    "Paladin": {
        1: [("Bless","Enchantment",False,True),("Command","Enchantment",False,False),
            ("Compelled Duel","Enchantment",False,True),("Cure Wounds","Evocation",False,False),
            ("Detect Evil and Good","Divination",False,True),("Detect Magic","Divination",True,True),
            ("Detect Poison and Disease","Divination",True,True),("Divine Favor","Evocation",False,True),
            ("Heroism","Enchantment",False,True),("Protection from Evil and Good","Abjuration",False,True),
            ("Purify Food and Drink","Transmutation",True,False),("Searing Smite","Evocation",False,True),
            ("Shield of Faith","Abjuration",False,True),("Thunderous Smite","Evocation",False,True),
            ("Wrathful Smite","Evocation",False,True),],
        2: [("Aid","Abjuration",False,False),("Branding Smite","Evocation",False,True),
            ("Find Steed","Conjuration",False,False),("Lesser Restoration","Abjuration",False,False),
            ("Locate Object","Divination",False,True),("Magic Weapon","Transmutation",False,True),
            ("Prayer of Healing","Evocation",False,False),("Protection from Poison","Abjuration",False,False),
            ("Zone of Truth","Enchantment",False,False),],
        3: [("Aura of Vitality","Evocation",False,True),("Blinding Smite","Evocation",False,True),
            ("Create Food and Water","Conjuration",False,False),("Crusader's Mantle","Evocation",False,True),
            ("Daylight","Evocation",False,False),("Dispel Magic","Abjuration",False,False),
            ("Elemental Weapon","Transmutation",False,True),("Magic Circle","Abjuration",False,False),
            ("Remove Curse","Abjuration",False,False),("Revivify","Necromancy",False,False),
            ("Spirit Shroud","Necromancy",False,True),],
        4: [("Aura of Life","Abjuration",False,True),("Aura of Purity","Abjuration",False,True),
            ("Banishment","Abjuration",False,True),("Death Ward","Abjuration",False,False),
            ("Guardian of Faith","Conjuration",False,False),("Locate Creature","Divination",False,True),
            ("Staggering Smite","Evocation",False,True),],
        5: [("Banishing Smite","Abjuration",False,True),("Circle of Power","Abjuration",False,True),
            ("Destructive Wave","Evocation",False,False),("Dispel Evil and Good","Abjuration",False,True),
            ("Geas","Enchantment",False,False),("Holy Weapon","Evocation",False,True),
            ("Raise Dead","Necromancy",False,False),("Summon Celestial","Conjuration",False,True),],
    },
    "Ranger": {
        1: [("Absorb Elements","Abjuration",False,False),("Alarm","Abjuration",True,False),
            ("Animal Friendship","Enchantment",False,False),("Cure Wounds","Evocation",False,False),
            ("Detect Magic","Divination",True,True),("Detect Poison and Disease","Divination",True,True),
            ("Ensnaring Strike","Conjuration",False,True),("Entangle","Conjuration",False,True),
            ("Fog Cloud","Conjuration",False,True),("Goodberry","Transmutation",False,False),
            ("Hail of Thorns","Conjuration",False,True),("Hunter's Mark","Divination",False,True),
            ("Jump","Transmutation",False,False),("Longstrider","Transmutation",False,False),
            ("Speak with Animals","Divination",True,False),],
        2: [("Animal Messenger","Enchantment",True,False),("Barkskin","Transmutation",False,True),
            ("Beast Sense","Divination",True,True),("Cordon of Arrows","Transmutation",False,False),
            ("Darkvision","Transmutation",False,False),("Find Traps","Divination",False,False),
            ("Gust of Wind","Evocation",False,True),("Lesser Restoration","Abjuration",False,False),
            ("Locate Animals or Plants","Divination",True,False),("Locate Object","Divination",False,True),
            ("Magic Weapon","Transmutation",False,True),("Pass without Trace","Abjuration",False,True),
            ("Protection from Poison","Abjuration",False,False),("Silence","Illusion",True,True),
            ("Spike Growth","Transmutation",False,True),],
        3: [("Conjure Animals","Conjuration",False,True),("Conjure Barrage","Conjuration",False,False),
            ("Daylight","Evocation",False,False),("Flame Arrows","Transmutation",False,True),
            ("Lightning Arrow","Transmutation",False,True),("Nondetection","Abjuration",False,False),
            ("Plant Growth","Transmutation",False,False),("Protection from Energy","Abjuration",False,True),
            ("Speak with Plants","Transmutation",False,False),("Water Breathing","Transmutation",True,False),
            ("Water Walk","Transmutation",True,False),("Wind Wall","Evocation",False,True),],
        4: [("Conjure Woodland Beings","Conjuration",False,True),("Freedom of Movement","Abjuration",False,False),
            ("Grasping Vine","Conjuration",False,True),("Locate Creature","Divination",False,True),
            ("Stoneskin","Abjuration",False,True),],
        5: [("Commune with Nature","Divination",True,False),("Conjure Volley","Conjuration",False,False),
            ("Greater Restoration","Abjuration",False,False),("Swift Quiver","Transmutation",False,True),
            ("Tree Stride","Conjuration",False,True),("Wrath of Nature","Evocation",False,True),],
    },
    "Sorcerer": {
        1: [("Burning Hands","Evocation",False,False),("Charm Person","Enchantment",False,False),
            ("Chromatic Orb","Evocation",False,False),("Color Spray","Illusion",False,False),
            ("Comprehend Languages","Divination",True,False),("Detect Magic","Divination",True,True),
            ("Disguise Self","Illusion",False,False),("Earth Tremor","Evocation",False,False),
            ("Expeditious Retreat","Transmutation",False,True),("False Life","Necromancy",False,False),
            ("Feather Fall","Transmutation",False,False),("Fog Cloud","Conjuration",False,True),
            ("Ice Knife","Conjuration",False,False),("Jump","Transmutation",False,False),
            ("Mage Armor","Abjuration",False,False),("Magic Missile","Evocation",False,False),
            ("Ray of Sickness","Necromancy",False,False),("Shield","Abjuration",False,False),
            ("Silent Image","Illusion",False,True),("Sleep","Enchantment",False,False),
            ("Thunderwave","Evocation",False,False),("Witch Bolt","Evocation",False,True),],
        2: [("Alter Self","Transmutation",False,True),("Blindness/Deafness","Necromancy",False,False),
            ("Blur","Illusion",False,True),("Cloud of Daggers","Conjuration",False,True),
            ("Crown of Madness","Enchantment",False,True),("Darkness","Evocation",False,True),
            ("Darkvision","Transmutation",False,False),("Detect Thoughts","Divination",False,True),
            ("Enhance Ability","Transmutation",False,True),("Enlarge/Reduce","Transmutation",False,True),
            ("Gust of Wind","Evocation",False,True),("Hold Person","Enchantment",False,True),
            ("Invisibility","Illusion",False,True),("Knock","Transmutation",False,False),
            ("Levitate","Transmutation",False,True),("Mirror Image","Illusion",False,False),
            ("Misty Step","Conjuration",False,False),("Phantasmal Force","Illusion",False,True),
            ("Scorching Ray","Evocation",False,False),("See Invisibility","Divination",False,False),
            ("Shatter","Evocation",False,False),("Spider Climb","Transmutation",False,True),
            ("Suggestion","Enchantment",False,True),("Web","Conjuration",False,True),],
        3: [("Blink","Transmutation",False,False),("Clairvoyance","Divination",False,True),
            ("Counterspell","Abjuration",False,False),("Daylight","Evocation",False,False),
            ("Dispel Magic","Abjuration",False,False),("Fear","Illusion",False,True),
            ("Fireball","Evocation",False,False),("Fly","Transmutation",False,True),
            ("Gaseous Form","Transmutation",False,True),("Haste","Transmutation",False,True),
            ("Hypnotic Pattern","Illusion",False,True),("Lightning Bolt","Evocation",False,False),
            ("Major Image","Illusion",False,True),("Protection from Energy","Abjuration",False,True),
            ("Sleet Storm","Conjuration",False,True),("Slow","Transmutation",False,True),
            ("Stinking Cloud","Conjuration",False,True),("Tongues","Divination",False,False),
            ("Water Breathing","Transmutation",True,False),("Water Walk","Transmutation",True,False),],
        4: [("Banishment","Abjuration",False,True),("Blight","Necromancy",False,False),
            ("Confusion","Enchantment",False,True),("Dimension Door","Conjuration",False,False),
            ("Dominate Beast","Enchantment",False,True),("Greater Invisibility","Illusion",False,True),
            ("Ice Storm","Evocation",False,False),("Polymorph","Transmutation",False,True),
            ("Stoneskin","Abjuration",False,True),("Wall of Fire","Evocation",False,True),],
        5: [("Animate Objects","Transmutation",False,True),("Cloudkill","Conjuration",False,True),
            ("Cone of Cold","Evocation",False,False),("Creation","Illusion",False,False),
            ("Dominate Person","Enchantment",False,True),("Hold Monster","Enchantment",False,True),
            ("Insect Plague","Conjuration",False,True),("Seeming","Illusion",False,False),
            ("Telekinesis","Transmutation",False,True),("Teleportation Circle","Conjuration",False,False),
            ("Wall of Stone","Evocation",False,True),],
        6: [("Arcane Gate","Conjuration",False,True),("Chain Lightning","Evocation",False,False),
            ("Circle of Death","Necromancy",False,False),("Disintegrate","Transmutation",False,False),
            ("Eyebite","Necromancy",False,True),("Globe of Invulnerability","Abjuration",False,True),
            ("Mass Suggestion","Enchantment",False,False),("Move Earth","Transmutation",False,True),
            ("Sunbeam","Evocation",False,True),("True Seeing","Divination",False,False),],
        7: [("Delayed Blast Fireball","Evocation",False,True),("Etherealness","Transmutation",False,False),
            ("Finger of Death","Necromancy",False,False),("Fire Storm","Evocation",False,False),
            ("Plane Shift","Conjuration",False,False),("Reverse Gravity","Transmutation",False,True),
            ("Teleport","Conjuration",False,False),],
        8: [("Dominate Monster","Enchantment",False,True),("Earthquake","Evocation",False,True),
            ("Incendiary Cloud","Conjuration",False,True),("Power Word Stun","Enchantment",False,False),
            ("Sunburst","Evocation",False,False),],
        9: [("Gate","Conjuration",False,True),("Meteor Swarm","Evocation",False,False),
            ("Power Word Kill","Enchantment",False,False),("Time Stop","Transmutation",False,False),
            ("Wish","Conjuration",False,False),],
    },
    "Warlock": {
        1: [("Armor of Agathys","Abjuration",False,False),("Arms of Hadar","Conjuration",False,False),
            ("Charm Person","Enchantment",False,False),("Comprehend Languages","Divination",True,False),
            ("Expeditious Retreat","Transmutation",False,True),("Hellish Rebuke","Evocation",False,False),
            ("Hex","Enchantment",False,True),("Illusory Script","Illusion",True,False),
            ("Protection from Evil and Good","Abjuration",False,True),("Unseen Servant","Conjuration",True,False),
            ("Witch Bolt","Evocation",False,True),],
        2: [("Cloud of Daggers","Conjuration",False,True),("Crown of Madness","Enchantment",False,True),
            ("Darkness","Evocation",False,True),("Enthrall","Enchantment",False,True),
            ("Hold Person","Enchantment",False,True),("Invisibility","Illusion",False,True),
            ("Mirror Image","Illusion",False,False),("Misty Step","Conjuration",False,False),
            ("Ray of Enfeeblement","Necromancy",False,True),("Shatter","Evocation",False,False),
            ("Spider Climb","Transmutation",False,True),("Suggestion","Enchantment",False,True),],
        3: [("Counterspell","Abjuration",False,False),("Dispel Magic","Abjuration",False,False),
            ("Fear","Illusion",False,True),("Fly","Transmutation",False,True),
            ("Gaseous Form","Transmutation",False,True),("Hunger of Hadar","Conjuration",False,True),
            ("Hypnotic Pattern","Illusion",False,True),("Magic Circle","Abjuration",False,False),
            ("Major Image","Illusion",False,True),("Remove Curse","Abjuration",False,False),
            ("Tongues","Divination",False,False),("Vampiric Touch","Necromancy",False,True),],
        4: [("Banishment","Abjuration",False,True),("Blight","Necromancy",False,False),
            ("Dimension Door","Conjuration",False,False),("Hallucinatory Terrain","Illusion",False,False),],
        5: [("Contact Other Plane","Divination",True,False),("Dream","Illusion",False,False),
            ("Hold Monster","Enchantment",False,True),("Jallarzi's Storm of Radiance","Evocation",False,True),
            ("Scrying","Divination",False,True),],
        6: [("Arcane Gate","Conjuration",False,True),("Circle of Death","Necromancy",False,False),
            ("Conjure Fey","Conjuration",False,True),("Create Undead","Necromancy",False,False),
            ("Eyebite","Necromancy",False,True),("Flesh to Stone","Transmutation",False,True),
            ("Mass Suggestion","Enchantment",False,False),("True Seeing","Divination",False,False),],
        7: [("Etherealness","Transmutation",False,False),("Finger of Death","Necromancy",False,False),
            ("Forcecage","Evocation",False,False),("Plane Shift","Conjuration",False,False),],
        8: [("Demiplane","Conjuration",False,False),("Dominate Monster","Enchantment",False,True),
            ("Feeblemind","Enchantment",False,False),("Glibness","Transmutation",False,False),
            ("Power Word Stun","Enchantment",False,False),],
        9: [("Astral Projection","Necromancy",False,False),("Foresight","Divination",False,False),
            ("Gate","Conjuration",False,True),("Imprisonment","Abjuration",False,False),
            ("Power Word Kill","Enchantment",False,False),("True Polymorph","Transmutation",False,True),],
    },
    "Wizard": {
        1: [("Absorb Elements","Abjuration",False,False),("Alarm","Abjuration",True,False),
            ("Burning Hands","Evocation",False,False),("Catapult","Transmutation",False,False),
            ("Cause Fear","Necromancy",False,True),("Charm Person","Enchantment",False,False),
            ("Chromatic Orb","Evocation",False,False),("Color Spray","Illusion",False,False),
            ("Comprehend Languages","Divination",True,False),("Detect Magic","Divination",True,True),
            ("Disguise Self","Illusion",False,False),("Earth Tremor","Evocation",False,False),
            ("Expeditious Retreat","Transmutation",False,True),("False Life","Necromancy",False,False),
            ("Feather Fall","Transmutation",False,False),("Find Familiar","Conjuration",True,False),
            ("Fog Cloud","Conjuration",False,True),("Grease","Conjuration",False,False),
            ("Ice Knife","Conjuration",False,False),("Identify","Divination",True,False),
            ("Illusory Script","Illusion",True,False),("Jump","Transmutation",False,False),
            ("Longstrider","Transmutation",False,False),("Mage Armor","Abjuration",False,False),
            ("Magic Missile","Evocation",False,False),("Protection from Evil and Good","Abjuration",False,True),
            ("Ray of Sickness","Necromancy",False,False),("Shield","Abjuration",False,False),
            ("Silent Image","Illusion",False,True),("Sleep","Enchantment",False,False),
            ("Tasha's Hideous Laughter","Enchantment",False,True),("Thunderwave","Evocation",False,False),
            ("Unseen Servant","Conjuration",True,False),("Witch Bolt","Evocation",False,True),],
        2: [("Alter Self","Transmutation",False,True),("Arcane Lock","Abjuration",False,False),
            ("Blindness/Deafness","Necromancy",False,False),("Blur","Illusion",False,True),
            ("Cloud of Daggers","Conjuration",False,True),("Continual Flame","Evocation",False,False),
            ("Crown of Madness","Enchantment",False,True),("Darkness","Evocation",False,True),
            ("Darkvision","Transmutation",False,False),("Detect Thoughts","Divination",False,True),
            ("Enlarge/Reduce","Transmutation",False,True),("Flaming Sphere","Conjuration",False,True),
            ("Gentle Repose","Necromancy",True,False),("Hold Person","Enchantment",False,True),
            ("Invisibility","Illusion",False,True),("Knock","Transmutation",False,False),
            ("Levitate","Transmutation",False,True),("Locate Object","Divination",False,True),
            ("Magic Mouth","Illusion",True,False),("Magic Weapon","Transmutation",False,True),
            ("Melf's Acid Arrow","Evocation",False,False),("Mirror Image","Illusion",False,False),
            ("Misty Step","Conjuration",False,False),("Nystul's Magic Aura","Illusion",False,False),
            ("Phantasmal Force","Illusion",False,True),("Ray of Enfeeblement","Necromancy",False,True),
            ("Rope Trick","Transmutation",False,False),("Scorching Ray","Evocation",False,False),
            ("See Invisibility","Divination",False,False),("Shatter","Evocation",False,False),
            ("Spider Climb","Transmutation",False,True),("Suggestion","Enchantment",False,True),
            ("Web","Conjuration",False,True),],
        3: [("Animate Dead","Necromancy",False,False),("Bestow Curse","Necromancy",False,True),
            ("Blink","Transmutation",False,False),("Clairvoyance","Divination",False,True),
            ("Counterspell","Abjuration",False,False),("Dispel Magic","Abjuration",False,False),
            ("Erupting Earth","Transmutation",False,False),("Fear","Illusion",False,True),
            ("Feign Death","Necromancy",True,False),("Fireball","Evocation",False,False),
            ("Fly","Transmutation",False,True),("Gaseous Form","Transmutation",False,True),
            ("Glyph of Warding","Abjuration",False,False),("Haste","Transmutation",False,True),
            ("Hypnotic Pattern","Illusion",False,True),("Leomund's Tiny Hut","Evocation",True,False),
            ("Lightning Bolt","Evocation",False,False),("Magic Circle","Abjuration",False,False),
            ("Major Image","Illusion",False,True),("Nondetection","Abjuration",False,False),
            ("Phantom Steed","Illusion",True,False),("Protection from Energy","Abjuration",False,True),
            ("Remove Curse","Abjuration",False,False),("Sending","Evocation",False,False),
            ("Sleet Storm","Conjuration",False,True),("Slow","Transmutation",False,True),
            ("Stinking Cloud","Conjuration",False,True),("Tongues","Divination",False,False),
            ("Vampiric Touch","Necromancy",False,True),("Water Breathing","Transmutation",True,False),],
        4: [("Arcane Eye","Divination",False,True),("Banishment","Abjuration",False,True),
            ("Blight","Necromancy",False,False),("Confusion","Enchantment",False,True),
            ("Conjure Minor Elementals","Conjuration",False,True),("Control Water","Transmutation",False,True),
            ("Dimension Door","Conjuration",False,False),("Divination","Divination",True,False),
            ("Evard's Black Tentacles","Conjuration",False,True),("Fabricate","Transmutation",False,False),
            ("Fire Shield","Evocation",False,False),("Greater Invisibility","Illusion",False,True),
            ("Hallucinatory Terrain","Illusion",False,False),("Ice Storm","Evocation",False,False),
            ("Leomund's Secret Chest","Conjuration",False,False),("Locate Creature","Divination",False,True),
            ("Mordenkainen's Faithful Hound","Conjuration",False,False),("Mordenkainen's Private Sanctum","Abjuration",False,False),
            ("Otiluke's Resilient Sphere","Evocation",False,True),("Phantasmal Killer","Illusion",False,True),
            ("Polymorph","Transmutation",False,True),("Stone Shape","Transmutation",False,False),
            ("Stoneskin","Abjuration",False,True),("Wall of Fire","Evocation",False,True),],
        5: [("Animate Objects","Transmutation",False,True),("Bigby's Hand","Evocation",False,True),
            ("Cloudkill","Conjuration",False,True),("Cone of Cold","Evocation",False,False),
            ("Conjure Elemental","Conjuration",False,True),("Contact Other Plane","Divination",True,False),
            ("Creation","Illusion",False,False),("Dominate Person","Enchantment",False,True),
            ("Dream","Illusion",False,False),("Geas","Enchantment",False,False),
            ("Hold Monster","Enchantment",False,True),("Legend Lore","Divination",False,False),
            ("Mislead","Illusion",False,True),("Modify Memory","Enchantment",False,True),
            ("Passwall","Transmutation",False,False),("Planar Binding","Abjuration",False,False),
            ("Rary's Telepathic Bond","Divination",True,False),("Scrying","Divination",False,True),
            ("Seeming","Illusion",False,False),("Skill Empowerment","Transmutation",False,True),
            ("Telekinesis","Transmutation",False,True),("Teleportation Circle","Conjuration",False,False),
            ("Wall of Force","Evocation",False,True),("Wall of Stone","Evocation",False,True),],
        6: [("Arcane Gate","Conjuration",False,True),("Chain Lightning","Evocation",False,False),
            ("Circle of Death","Necromancy",False,False),("Contingency","Evocation",False,False),
            ("Create Undead","Necromancy",False,False),("Disintegrate","Transmutation",False,False),
            ("Eyebite","Necromancy",False,True),("Flesh to Stone","Transmutation",False,True),
            ("Globe of Invulnerability","Abjuration",False,True),("Guards and Wards","Abjuration",False,False),
            ("Instant Summons","Conjuration",True,False),("Magic Jar","Necromancy",False,True),
            ("Mass Suggestion","Enchantment",False,False),("Move Earth","Transmutation",False,True),
            ("Otiluke's Freezing Sphere","Evocation",False,False),("Otto's Irresistible Dance","Enchantment",False,True),
            ("Programmed Illusion","Illusion",False,False),("Sunbeam","Evocation",False,True),
            ("True Seeing","Divination",False,False),("Wall of Ice","Evocation",False,True),],
        7: [("Delayed Blast Fireball","Evocation",False,True),("Etherealness","Transmutation",False,False),
            ("Finger of Death","Necromancy",False,False),("Forcecage","Evocation",False,False),
            ("Mirage Arcane","Illusion",False,False),("Mordenkainen's Magnificent Mansion","Conjuration",False,False),
            ("Mordenkainen's Sword","Evocation",False,True),("Plane Shift","Conjuration",False,False),
            ("Prismatic Spray","Evocation",False,False),("Project Image","Illusion",False,True),
            ("Reverse Gravity","Transmutation",False,True),("Sequester","Transmutation",False,False),
            ("Simulacrum","Illusion",False,False),("Symbol","Abjuration",False,False),
            ("Teleport","Conjuration",False,False),],
        8: [("Antimagic Field","Abjuration",False,True),("Antipathy/Sympathy","Enchantment",False,False),
            ("Clone","Necromancy",False,False),("Control Weather","Transmutation",False,True),
            ("Demiplane","Conjuration",False,False),("Dominate Monster","Enchantment",False,True),
            ("Feeblemind","Enchantment",False,False),("Incendiary Cloud","Conjuration",False,True),
            ("Maze","Conjuration",False,True),("Mind Blank","Abjuration",False,False),
            ("Power Word Stun","Enchantment",False,False),("Sunburst","Evocation",False,False),
            ("Telepathy","Evocation",False,True),],
        9: [("Astral Projection","Necromancy",False,False),("Foresight","Divination",False,False),
            ("Gate","Conjuration",False,True),("Imprisonment","Abjuration",False,False),
            ("Meteor Swarm","Evocation",False,False),("Power Word Kill","Enchantment",False,False),
            ("Prismatic Wall","Abjuration",False,False),("Shapechange","Transmutation",False,True),
            ("Time Stop","Transmutation",False,False),("True Polymorph","Transmutation",False,True),
            ("Weird","Illusion",False,True),("Wish","Conjuration",False,False),],
    },
}

# Spells for half-casters (Paladin, Ranger) use their own lists above
# For Artificer, use SPELLS["Artificer"] above

def get_spells_for_class(cls: str, level: int) -> dict:
    """Return {spell_level: [(name, school, ritual, conc)]} available at this char level."""
    from dnd_data import CLASS_SPELLCASTING, FULL_CASTER_SLOTS, HALF_CASTER_SLOTS, WARLOCK_SLOTS
    sc = CLASS_SPELLCASTING.get(cls)
    if not sc:
        return {}
    ctype = sc["type"]
    if ctype == "full":
        slots = FULL_CASTER_SLOTS.get(level, [0]*9)
    elif ctype == "half":
        slots = HALF_CASTER_SLOTS.get(level, [0]*9)
    elif ctype == "warlock":
        count, slot_level = WARLOCK_SLOTS.get(level, (0, 0))
        slots = [0]*9
        if slot_level > 0:
            slots[slot_level - 1] = count
    else:
        return {}
    result = {"cantrips": CANTRIPS.get(cls, [])}
    spell_data = SPELLS.get(cls, {})
    for i, count in enumerate(slots, start=1):
        if count > 0 and i in spell_data:
            result[i] = spell_data[i]
    return result
