_CR_XP = {
    0: 10, 0.125: 25, 0.25: 50, 0.5: 100, 1: 200, 2: 450, 3: 700, 4: 1100,
    5: 1800, 6: 2300, 7: 2900, 8: 3900, 9: 5000, 10: 5900, 11: 7200, 12: 8400,
    13: 10000, 14: 11500, 15: 13000, 16: 15000, 17: 18000, 18: 20000, 19: 22000,
    20: 25000, 21: 33000, 22: 41000, 23: 50000, 24: 62000, 30: 155000,
}

def _e(cr, type_, size, alignment, hp, ac, init, attacks, special=None,
       res=None, imm=None, cond_imm=None, desc="", tags=None):
    return {
        "cr": cr, "xp": _CR_XP.get(cr, 0),
        "type": type_, "size": size, "alignment": alignment,
        "hp": hp, "ac": ac, "initiative_mod": init,
        "attacks": attacks,
        "special_abilities": special or [],
        "resistances": res or [],
        "immunities": imm or [],
        "condition_immunities": cond_imm or [],
        "desc": desc,
        "tags": tags or [],
    }

def _atk(name, bonus, damage, damage_type):
    return {"name": name, "bonus": bonus, "damage": damage, "damage_type": damage_type}


ENEMIES = {

    # ── CR 0 ──────────────────────────────────────────────────────────────────
    "Rat": _e(
        0, "Beast", "Tiny", "unaligned", 1, 10, 0,
        [_atk("Bite", 0, "1", "piercing")],
        desc="A disease-carrying rodent, dangerous only in swarms.",
        tags=["beast", "dungeon", "sewer", "swarm"],
    ),
    "Spider": _e(
        0, "Beast", "Tiny", "unaligned", 1, 12, 2,
        [_atk("Bite", 1, "1", "piercing")],
        special=["Poison Bite: DC 9 Con save or take 2 poison damage"],
        desc="A venomous eight-legged crawler.",
        tags=["beast", "dungeon", "cave", "forest"],
    ),
    "Bat": _e(
        0, "Beast", "Tiny", "unaligned", 1, 12, 2,
        [_atk("Bite", 0, "1", "piercing")],
        desc="A nocturnal flier, harmless alone but unnerving in numbers.",
        tags=["beast", "cave", "dungeon"],
    ),

    # ── CR 1/8 ────────────────────────────────────────────────────────────────
    "Bandit": _e(
        0.125, "Humanoid", "Medium", "chaotic neutral", 11, 12, 1,
        [_atk("Scimitar", 3, "1d6+1", "slashing")],
        desc="A desperate criminal who preys on travelers.",
        tags=["humanoid", "road", "forest", "urban"],
    ),
    "Cultist": _e(
        0.125, "Humanoid", "Medium", "chaotic evil", 9, 12, 1,
        [_atk("Scimitar", 3, "1d6+1", "slashing")],
        desc="A zealot bound to a dark patron, willing to die for their cause.",
        tags=["humanoid", "undead", "dungeon", "urban"],
    ),
    "Giant Rat": _e(
        0.125, "Beast", "Small", "unaligned", 7, 12, 2,
        [_atk("Bite", 4, "1d4+2", "piercing")],
        special=["Pack Tactics: advantage on attacks if ally is adjacent to target"],
        desc="An oversized rodent that hunts in packs in sewers and ruins.",
        tags=["beast", "dungeon", "sewer", "swarm"],
    ),
    "Guard": _e(
        0.125, "Humanoid", "Medium", "any", 11, 16, 1,
        [_atk("Spear", 3, "1d6+1", "piercing")],
        desc="A city watchman or hired soldier standing post.",
        tags=["humanoid", "urban", "civilized"],
    ),
    "Kobold": _e(
        0.125, "Humanoid", "Small", "lawful evil", 5, 12, 2,
        [_atk("Dagger", 4, "1d4+2", "piercing")],
        special=["Pack Tactics: advantage when ally is adjacent to target",
                 "Sunlight Sensitivity: disadvantage in direct sunlight"],
        desc="A small reptilian humanoid that serves dragons and mines in dark tunnels.",
        tags=["humanoid", "koboldoid", "dungeon", "cave", "dragon"],
    ),
    "Stirge": _e(
        0.125, "Beast", "Tiny", "unaligned", 2, 14, 3,
        [_atk("Blood Drain", 5, "1d4+3", "piercing")],
        special=["Blood Drain: attaches on hit, drains 1d4+3 each turn automatically"],
        desc="A mosquito-like creature that latches on and drains blood.",
        tags=["beast", "cave", "dungeon", "swamp"],
    ),
    "Twig Blight": _e(
        0.125, "Plant", "Small", "neutral evil", 4, 13, 1,
        [_atk("Claws", 3, "1d4+1", "piercing")],
        imm=["blinded", "deafened", "exhaustion"],
        desc="An animated twig-like plant creature spawned by dark magic.",
        tags=["plant", "forest", "undead", "blight"],
    ),

    # ── CR 1/4 ────────────────────────────────────────────────────────────────
    "Goblin": _e(
        0.25, "Humanoid", "Small", "neutral evil", 7, 15, 2,
        [_atk("Scimitar", 4, "1d6+2", "slashing")],
        special=["Nimble Escape: can Disengage or Hide as bonus action"],
        desc="A cunning, cowardly humanoid that raids in packs from caves and ruins.",
        tags=["humanoid", "goblinoid", "cave", "forest", "dungeon"],
    ),
    "Needle Blight": _e(
        0.25, "Plant", "Small", "neutral evil", 11, 12, 1,
        [_atk("Claws", 3, "1d4+1", "piercing")],
        desc="A thorn-covered plant creature that hurls needles at prey.",
        tags=["plant", "forest", "blight"],
    ),
    "Skeleton": _e(
        0.25, "Undead", "Medium", "lawful evil", 13, 13, 2,
        [_atk("Shortsword", 4, "1d6+2", "piercing")],
        imm=["poison", "exhaustion"],
        cond_imm=["exhaustion", "poisoned"],
        res=["piercing", "bludgeoning"],
        desc="Animated bones of the dead, mindlessly obedient to their necromancer.",
        tags=["undead", "dungeon", "tomb", "necromancy"],
    ),
    "Winged Kobold": _e(
        0.25, "Humanoid", "Small", "lawful evil", 7, 13, 3,
        [_atk("Dagger", 4, "1d4+2", "piercing")],
        special=["Drop Rock: 1d6 bludgeoning from above while flying"],
        desc="A winged kobold that dive-bombs foes from the air.",
        tags=["humanoid", "koboldoid", "cave", "dungeon"],
    ),
    "Wolf": _e(
        0.25, "Beast", "Medium", "unaligned", 11, 13, 2,
        [_atk("Bite", 4, "2d4+2", "piercing")],
        special=["Pack Tactics: advantage when ally is adjacent to target",
                 "Knockdown: DC 11 Str save or be knocked prone on hit"],
        desc="A predatory canine that hunts in coordinated packs.",
        tags=["beast", "forest", "tundra"],
    ),
    "Zombie": _e(
        0.25, "Undead", "Medium", "neutral evil", 22, 8, -2,
        [_atk("Slam", 3, "1d6+1", "bludgeoning")],
        special=["Undead Fortitude: on lethal hit DC 5+damage Con save to drop to 1 HP instead"],
        imm=["poison"],
        cond_imm=["poisoned"],
        desc="A rotting corpse animated by dark magic, relentlessly shambling forward.",
        tags=["undead", "dungeon", "tomb", "necromancy"],
    ),

    # ── CR 1/2 ────────────────────────────────────────────────────────────────
    "Gnoll": _e(
        0.5, "Humanoid", "Medium", "chaotic evil", 22, 15, 1,
        [_atk("Spear", 4, "1d6+2", "piercing")],
        special=["Rampage: when it reduces a creature to 0 HP, can move and make a bonus Bite attack"],
        desc="A savage hyena-headed humanoid that descends on prey in frenzied raids.",
        tags=["humanoid", "gnoll", "grassland", "dungeon"],
    ),
    "Hobgoblin": _e(
        0.5, "Humanoid", "Medium", "lawful evil", 11, 18, 1,
        [_atk("Longsword", 3, "1d8+1", "slashing")],
        special=["Martial Advantage: once per turn deal extra 2d6 if ally is adjacent to target"],
        desc="A militaristic goblinoid that fights in disciplined formations.",
        tags=["humanoid", "goblinoid", "dungeon", "fortress"],
    ),
    "Lizardfolk": _e(
        0.5, "Humanoid", "Medium", "neutral", 22, 15, 1,
        [_atk("Bite", 4, "1d6+2", "piercing")],
        desc="A cold-blooded reptilian tribesperson who guards swamp territory fiercely.",
        tags=["humanoid", "lizardfolk", "swamp", "coast"],
    ),
    "Orc": _e(
        0.5, "Humanoid", "Medium", "chaotic evil", 15, 13, 1,
        [_atk("Greataxe", 5, "1d12+3", "slashing")],
        special=["Aggressive: can move up to speed toward a hostile creature as bonus action"],
        desc="A fierce, brutish warrior driven by aggression and tribal fury.",
        tags=["humanoid", "orc", "mountain", "forest", "dungeon"],
    ),
    "Scout": _e(
        0.5, "Humanoid", "Medium", "any", 16, 13, 2,
        [_atk("Shortsword", 4, "1d6+2", "piercing")],
        special=["Keen Hearing and Sight: advantage on Perception checks"],
        desc="A trained wilderness ranger who excels at ambush and skirmish.",
        tags=["humanoid", "forest", "road", "wilderness"],
    ),
    "Shadow": _e(
        0.5, "Undead", "Medium", "chaotic evil", 16, 12, 2,
        [_atk("Strength Drain", 4, "2d6+2", "necrotic")],
        special=["Strength Drain: reduces target's Str by 1d4 on hit; creature dies if Str reaches 0",
                 "Amorphous: can move through 1-inch gaps"],
        res=["acid", "cold", "fire", "lightning", "thunder",
             "bludgeoning", "piercing", "slashing"],
        imm=["necrotic", "poison"],
        cond_imm=["exhaustion", "frightened", "grappled", "paralyzed", "poisoned"],
        desc="A creature of living darkness that drains the strength from the living.",
        tags=["undead", "dungeon", "shadow", "necromancy"],
    ),
    "Thug": _e(
        0.5, "Humanoid", "Medium", "any non-good", 32, 11, 0,
        [_atk("Mace", 4, "1d6+2", "bludgeoning")],
        special=["Pack Tactics: advantage when ally is adjacent to target"],
        desc="A hired muscle enforcer who relies on numbers and brutality.",
        tags=["humanoid", "urban", "criminal"],
    ),
    "Vine Blight": _e(
        0.5, "Plant", "Medium", "neutral evil", 26, 12, -1,
        [_atk("Constrict", 4, "2d6+2", "bludgeoning")],
        special=["Constrict: target is grappled and restrained on hit"],
        cond_imm=["blinded", "deafened", "exhaustion"],
        desc="A mass of animated vines that grapples prey and slowly crushes it.",
        tags=["plant", "forest", "swamp", "blight"],
    ),

    # ── CR 1 ──────────────────────────────────────────────────────────────────
    "Bugbear": _e(
        1, "Humanoid", "Medium", "chaotic evil", 27, 14, 2,
        [_atk("Morningstar", 4, "2d8+2", "piercing")],
        special=["Surprise Attack: extra 2d6 damage if target hasn't acted yet this combat"],
        desc="A large, savage goblinoid that ambushes prey with brutal strength.",
        tags=["humanoid", "goblinoid", "cave", "forest", "dungeon"],
    ),
    "Death Dog": _e(
        1, "Monstrosity", "Medium", "neutral evil", 39, 12, 2,
        [_atk("Bite", 4, "1d6+2", "piercing")],
        special=["Two-Headed: advantage on Perception and saves against blindness/deafness",
                 "Rotting Bite: DC 12 Con save or gain a disease that prevents HP recovery"],
        desc="A two-headed undead hound whose bite carries a rotting curse.",
        tags=["monstrosity", "undead", "dungeon", "desert"],
    ),
    "Dire Wolf": _e(
        1, "Beast", "Large", "unaligned", 37, 14, 2,
        [_atk("Bite", 5, "2d6+3", "piercing")],
        special=["Pack Tactics: advantage when ally is adjacent to target",
                 "Knockdown: DC 13 Str save or be knocked prone on hit"],
        desc="A massive prehistoric wolf, the apex predator of dark forests.",
        tags=["beast", "forest", "tundra", "cave"],
    ),
    "Ghoul": _e(
        1, "Undead", "Medium", "chaotic evil", 22, 12, 2,
        [_atk("Claws", 4, "2d4+2", "slashing")],
        special=["Paralyzing Claws: DC 10 Con save or paralyzed until end of next turn (not elves)"],
        imm=["poison"],
        cond_imm=["charmed", "exhaustion", "poisoned"],
        desc="A flesh-hungry undead that paralyzes prey with its claws before feeding.",
        tags=["undead", "dungeon", "tomb", "graveyard"],
    ),
    "Giant Spider": _e(
        1, "Beast", "Large", "unaligned", 26, 14, 3,
        [_atk("Bite", 5, "1d8+3", "piercing")],
        special=["Poison Bite: DC 11 Con save or 2d8 poison and paralyzed",
                 "Web: restrain target, DC 12 Str to escape"],
        desc="A man-sized arachnid that builds massive sticky webs in dark places.",
        tags=["beast", "dungeon", "cave", "forest"],
    ),
    "Harpy": _e(
        1, "Monstrosity", "Medium", "chaotic evil", 38, 11, 1,
        [_atk("Claws", 3, "2d4+1", "slashing")],
        special=["Luring Song: DC 11 Wis save or charmed and compelled to move toward harpy"],
        desc="A winged fiend with a woman's torso and a bird's body that lures sailors to doom.",
        tags=["monstrosity", "coastal", "mountain", "forest"],
    ),
    "Imp": _e(
        1, "Fiend", "Tiny", "lawful evil", 10, 13, 3,
        [_atk("Sting", 5, "1d4+3", "piercing")],
        special=["Poison Sting: DC 11 Con save or 3d4 poison",
                 "Shapechanger: can polymorph into rat, raven, or spider",
                 "Devil's Sight: sees normally in magical darkness"],
        res=["cold", "bludgeoning", "piercing", "slashing"],
        imm=["fire", "poison"],
        cond_imm=["poisoned"],
        desc="A tiny devil familiar that serves powerful spellcasters and warlocks.",
        tags=["fiend", "devil", "shapechanger", "planar"],
    ),
    "Specter": _e(
        1, "Undead", "Medium", "chaotic evil", 22, 12, 2,
        [_atk("Life Drain", 4, "3d6", "necrotic")],
        special=["Life Drain: target's HP maximum reduced by damage dealt until long rest"],
        res=["acid", "cold", "fire", "lightning", "thunder",
             "bludgeoning", "piercing", "slashing"],
        imm=["necrotic", "poison"],
        cond_imm=["charmed", "exhaustion", "grappled", "paralyzed", "petrified",
                  "poisoned", "prone", "restrained"],
        desc="The tormented spirit of a person who died in anguish, draining life from the living.",
        tags=["undead", "dungeon", "tomb", "ghost"],
    ),
    "Yuan-ti Pureblood": _e(
        1, "Humanoid", "Medium", "neutral evil", 40, 11, 1,
        [_atk("Scimitar", 4, "1d6+2", "slashing")],
        special=["Magic Resistance: advantage on saves against spells",
                 "Poison Immunity"],
        imm=["poison"],
        cond_imm=["poisoned"],
        desc="A humanoid yuan-ti cultist who appears nearly human but serves the serpent god.",
        tags=["humanoid", "yuan-ti", "dungeon", "jungle", "serpent"],
    ),

    # ── CR 2 ──────────────────────────────────────────────────────────────────
    "Azer": _e(
        2, "Elemental", "Medium", "lawful neutral", 39, 17, 1,
        [_atk("Warhammer", 5, "1d8+3", "bludgeoning")],
        special=["Heated Body: touching or hitting azer in melee deals 1d10 fire",
                 "Heated Weapons: melee attacks deal +1d6 fire"],
        imm=["fire", "poison"],
        cond_imm=["poisoned"],
        desc="A dwarf-like elemental being made of living bronze and flame from the Elemental Plane of Fire.",
        tags=["elemental", "fire", "planar", "dungeon"],
    ),
    "Bandit Captain": _e(
        2, "Humanoid", "Medium", "any non-lawful", 65, 15, 2,
        [_atk("Scimitar", 5, "1d6+3", "slashing")],
        special=["Multiattack: two Scimitar attacks plus one Dagger attack"],
        desc="A ruthless criminal leader with tactical experience and loyal thugs.",
        tags=["humanoid", "road", "forest", "urban", "criminal"],
    ),
    "Cult Fanatic": _e(
        2, "Humanoid", "Medium", "any non-good", 33, 13, 1,
        [_atk("Dagger", 4, "1d4+2", "piercing")],
        special=["Spellcasting: inflict wounds, hold person, spiritual weapon",
                 "Dark Devotion: advantage on saves against charmed and frightened"],
        desc="A fanatical priest of a dark deity who fights with spell and blade.",
        tags=["humanoid", "cultist", "dungeon", "urban", "planar"],
    ),
    "Ettercap": _e(
        2, "Monstrosity", "Medium", "neutral evil", 44, 13, 3,
        [_atk("Bite", 4, "1d8+2", "piercing")],
        special=["Poison Bite: DC 11 Con save or poisoned for 1 minute",
                 "Web: restrain target at range, DC 11 Str to escape",
                 "Spider Climb: moves on walls and ceilings"],
        desc="A spider-humanoid hybrid that tends web traps and herds giant spiders.",
        tags=["monstrosity", "forest", "cave", "spider"],
    ),
    "Gargoyle": _e(
        2, "Elemental", "Medium", "chaotic evil", 52, 15, 0,
        [_atk("Claws", 4, "1d6+2", "slashing")],
        special=["False Appearance: looks like a stone statue while motionless",
                 "Multiattack: two Claw attacks"],
        res=["bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["exhaustion", "petrified", "poisoned"],
        desc="A winged stone creature that perches on parapets and ambushes the unwary.",
        tags=["elemental", "dungeon", "castle", "mountain", "urban"],
    ),
    "Gelatinous Cube": _e(
        2, "Ooze", "Large", "unaligned", 84, 6, -3,
        [_atk("Pseudopod", 4, "3d6", "acid")],
        special=["Engulf: moves through space of Medium or smaller creature; DC 12 Dex save or engulfed",
                 "Transparent: DC 15 Perception to notice"],
        cond_imm=["blinded", "charmed", "deafened", "exhaustion", "frightened", "prone"],
        desc="A perfectly transparent ten-foot cube of acid that silently engulfs dungeon wanderers.",
        tags=["ooze", "dungeon"],
    ),
    "Ghast": _e(
        2, "Undead", "Medium", "chaotic evil", 36, 13, 3,
        [_atk("Bite", 3, "2d8+1", "piercing")],
        special=["Stench: DC 10 Con save or poisoned while within 5 ft",
                 "Paralyzing Claws: DC 10 Con save or paralyzed (elves immune)"],
        res=["necrotic"],
        imm=["poison"],
        cond_imm=["charmed", "exhaustion", "poisoned"],
        desc="A more powerful ghoul, reeking of death, whose stench sickens even the strong.",
        tags=["undead", "dungeon", "tomb", "graveyard"],
    ),
    "Mimic": _e(
        2, "Monstrosity", "Medium", "neutral", 58, 12, 1,
        [_atk("Pseudopod", 5, "1d8+3", "bludgeoning")],
        special=["Shapechanger: can polymorph into any object",
                 "Adhesive: creature that touches mimic is grappled, DC 13 Str to escape",
                 "False Appearance: indistinguishable from mundane object"],
        cond_imm=["prone"],
        desc="A shape-shifting predator that disguises itself as treasure chests or doors.",
        tags=["monstrosity", "shapechanger", "dungeon"],
    ),
    "Ochre Jelly": _e(
        2, "Ooze", "Large", "unaligned", 45, 8, -2,
        [_atk("Pseudopod", 5, "2d6+3", "bludgeoning")],
        special=["Split: when damaged by lightning or slashing, splits into two smaller jellies"],
        res=["acid", "lightning"],
        imm=["cold", "lightning", "slashing"],
        cond_imm=["blinded", "charmed", "deafened", "exhaustion", "frightened", "prone"],
        desc="A corrosive amber ooze that dissolves flesh and seeps through cracks.",
        tags=["ooze", "dungeon", "cave"],
    ),
    "Priest": _e(
        2, "Humanoid", "Medium", "any", 27, 13, 1,
        [_atk("Mace", 2, "1d6", "bludgeoning")],
        special=["Spellcasting: cure wounds, guiding bolt, sacred flame, hold person",
                 "Divine Eminence: once per turn deals extra 2d6 radiant if spell slot used"],
        desc="A devoted servant of a deity who wields divine magic in combat.",
        tags=["humanoid", "urban", "civilized", "religious"],
    ),
    "Sea Hag": _e(
        2, "Fey", "Medium", "chaotic evil", 52, 14, 1,
        [_atk("Claws", 5, "2d6+3", "slashing")],
        special=["Death Glare: target that can see hag DC 11 Wis save or frightened",
                 "Horrifying Appearance: non-hags that see her DC 11 Wis save or frightened for 1 minute"],
        desc="A hideous sea witch who haunts coastal ruins and lures sailors to their deaths.",
        tags=["fey", "hag", "coastal", "swamp", "cave"],
    ),
    "Wererat": _e(
        2, "Humanoid", "Medium", "lawful evil", 33, 12, 2,
        [_atk("Shortsword", 4, "1d6+2", "piercing")],
        special=["Shapechanger: can polymorph to rat or hybrid form",
                 "Lycanthropy: bite can infect with wererat lycanthropy"],
        res=["bludgeoning", "piercing", "slashing"],
        desc="A humanoid infected with rat lycanthropy, cunning and disease-ridden.",
        tags=["humanoid", "shapechanger", "lycanthrope", "urban", "sewer"],
    ),
    "Will-o'-Wisp": _e(
        2, "Undead", "Tiny", "chaotic evil", 22, 19, 9,
        [_atk("Shock", 4, "2d8", "lightning")],
        special=["Consume Life: can drain dying creature to regain 10d6 HP",
                 "Incorporeal: can move through objects",
                 "Variable Illumination: can dim or brighten its glow"],
        res=["acid", "cold", "fire", "necrotic", "thunder",
             "bludgeoning", "piercing", "slashing"],
        imm=["lightning", "poison"],
        cond_imm=["exhaustion", "grappled", "paralyzed", "poisoned", "prone",
                  "restrained", "unconscious"],
        desc="A malevolent floating light that lures travelers into bogs and watches them die.",
        tags=["undead", "swamp", "forest", "dungeon"],
    ),

    # ── CR 3 ──────────────────────────────────────────────────────────────────
    "Bearded Devil": _e(
        3, "Fiend", "Medium", "lawful evil", 52, 13, 2,
        [_atk("Glaive", 5, "1d10+3", "slashing")],
        special=["Beard: DC 12 Con save or poisoned and can't regain HP for 1 minute",
                 "Steadfast: can't be frightened while devils nearby"],
        res=["cold", "bludgeoning", "piercing", "slashing"],
        imm=["fire", "poison"],
        cond_imm=["poisoned"],
        desc="A devil with a beard of writhing iron filaments whose touch poisons the wounded.",
        tags=["fiend", "devil", "planar", "dungeon"],
    ),
    "Bugbear Chief": _e(
        3, "Humanoid", "Medium", "chaotic evil", 65, 17, 2,
        [_atk("Morningstar", 5, "2d8+3", "piercing")],
        special=["Surprise Attack: extra 2d6 if target hasn't acted this combat",
                 "Brute: melee weapon attacks deal one extra die of damage (included)"],
        desc="The dominant bugbear of a tribe, more cunning and brutal than its kin.",
        tags=["humanoid", "goblinoid", "cave", "dungeon"],
    ),
    "Green Hag": _e(
        3, "Fey", "Medium", "neutral evil", 82, 17, 1,
        [_atk("Claws", 6, "2d8+4", "slashing")],
        special=["Mimicry: can mimic animal sounds and humanoid voices",
                 "Illusory Appearance: looks like a beautiful young woman until dispelled",
                 "Weakness: can curse a creature to have disadvantage on ability checks"],
        desc="A wicked shapeshifting hag who preys on desires and slowly destroys her victims.",
        tags=["fey", "hag", "forest", "swamp", "cave"],
    ),
    "Hell Hound": _e(
        3, "Fiend", "Medium", "lawful evil", 45, 15, 1,
        [_atk("Bite", 5, "1d8+3", "piercing")],
        special=["Fire Breath: 15-ft cone, DC 12 Dex save or 6d6 fire",
                 "Pack Tactics: advantage when ally is adjacent to target"],
        imm=["fire"],
        desc="A fiery hound from the Nine Hells that hunts in packs for its devil masters.",
        tags=["fiend", "fire", "planar", "dungeon"],
    ),
    "Knight": _e(
        3, "Humanoid", "Medium", "any", 52, 18, 0,
        [_atk("Greatsword", 5, "2d6+3", "slashing")],
        special=["Multiattack: two Greatsword attacks",
                 "Leadership: allies within 30 ft add 1d4 to attack rolls for 1 minute"],
        desc="A heavily armored warrior sworn to a lord or code of conduct.",
        tags=["humanoid", "urban", "civilized", "military"],
    ),
    "Manticore": _e(
        3, "Monstrosity", "Large", "lawful evil", 68, 14, 1,
        [_atk("Bite", 6, "1d8+4", "piercing")],
        special=["Tail Spike: ranged attack +4, 1d8+2 piercing up to 100 ft (24 spikes total)",
                 "Multiattack: two Claw attacks plus one Bite"],
        desc="A winged lion with a human face and a spike-studded tail that fires like a barrage.",
        tags=["monstrosity", "mountain", "desert", "flying"],
    ),
    "Minotaur": _e(
        3, "Monstrosity", "Large", "chaotic evil", 114, 14, 0,
        [_atk("Greataxe", 6, "2d12+4", "slashing")],
        special=["Charge: if moves 10 ft before hit, extra 2d12 piercing and DC 14 Str save or prone",
                 "Labyrinthine Recall: can perfectly recall any path it has traveled",
                 "Reckless: can attack with advantage; attacks against it also have advantage"],
        desc="A savage bull-headed giant that haunts labyrinths and underground ruins.",
        tags=["monstrosity", "dungeon", "labyrinth", "cave"],
    ),
    "Mummy": _e(
        3, "Undead", "Medium", "lawful evil", 58, 11, -1,
        [_atk("Rotting Fist", 5, "2d6+3", "bludgeoning")],
        special=["Dreadful Glare: DC 11 Wis save or frightened",
                 "Rotting Curse: target cursed; max HP reduced by 10 until remove curse cast"],
        res=["bludgeoning", "piercing", "slashing"],
        imm=["necrotic", "poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "paralyzed", "poisoned"],
        desc="An ancient embalmed corpse bound by burial rites, rising to punish tomb-robbers.",
        tags=["undead", "tomb", "dungeon", "desert"],
    ),
    "Owlbear": _e(
        3, "Monstrosity", "Large", "unaligned", 59, 13, 1,
        [_atk("Claws", 7, "2d8+5", "slashing")],
        special=["Keen Sight and Smell: advantage on Perception",
                 "Multiattack: one Beak and one Claws attack"],
        desc="A territorial hybrid of owl and bear, ferocious beyond reason.",
        tags=["monstrosity", "forest", "cave", "mountain"],
    ),
    "Phase Spider": _e(
        3, "Monstrosity", "Large", "unaligned", 32, 13, 3,
        [_atk("Bite", 5, "1d10+3", "piercing")],
        special=["Poison Bite: DC 11 Con save or 4d8 poison",
                 "Ethereal Jaunt: bonus action to shift to/from Ethereal Plane"],
        desc="A giant spider that phases in and out of the Ethereal Plane to ambush prey.",
        tags=["monstrosity", "spider", "dungeon", "cave", "ethereal"],
    ),
    "Veteran": _e(
        3, "Humanoid", "Medium", "any", 58, 17, 1,
        [_atk("Longsword", 5, "1d8+3", "slashing")],
        special=["Multiattack: two Longsword attacks"],
        desc="A battle-hardened soldier with years of combat experience.",
        tags=["humanoid", "urban", "military", "civilized"],
    ),
    "Werewolf": _e(
        3, "Humanoid", "Medium", "chaotic evil", 58, 12, 1,
        [_atk("Claws", 4, "2d4+2", "slashing")],
        special=["Shapechanger: polymorph to wolf or hybrid form",
                 "Lycanthropy: bite in hybrid form can infect with lycanthropy"],
        res=["bludgeoning", "piercing", "slashing"],
        desc="A human cursed with wolf lycanthropy, losing control under the full moon.",
        tags=["humanoid", "shapechanger", "lycanthrope", "forest"],
    ),
    "Wight": _e(
        3, "Undead", "Medium", "neutral evil", 45, 14, 3,
        [_atk("Longsword", 4, "1d8+2", "slashing")],
        special=["Life Drain: DC 13 Con save or max HP reduced by damage amount until long rest",
                 "Create Spawn: humanoids killed by life drain rise as zombies"],
        res=["necrotic", "bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["exhaustion", "poisoned"],
        desc="A will-driven undead warrior who drains life and creates undead from those it kills.",
        tags=["undead", "dungeon", "tomb", "necromancy"],
    ),
    "Winter Wolf": _e(
        3, "Monstrosity", "Large", "neutral evil", 75, 13, 1,
        [_atk("Bite", 6, "2d6+4", "piercing")],
        special=["Cold Breath: 15-ft cone, DC 12 Dex save or 4d8 cold",
                 "Pack Tactics: advantage when ally is adjacent to target"],
        imm=["cold"],
        desc="A giant wolf of the frozen north with an icy breath that can freeze prey solid.",
        tags=["monstrosity", "tundra", "mountain", "arctic"],
    ),

    # ── CR 4 ──────────────────────────────────────────────────────────────────
    "Banshee": _e(
        4, "Undead", "Medium", "chaotic evil", 58, 12, 2,
        [_atk("Corrupting Touch", 4, "3d6", "necrotic")],
        special=["Horrifying Visage: DC 13 Wis save or aged 1d4×10 years and frightened",
                 "Wail: once per day, all non-undead in 30 ft DC 13 Con save or drop to 0 HP"],
        res=["acid", "fire", "lightning", "thunder",
             "bludgeoning", "piercing", "slashing"],
        imm=["cold", "necrotic", "poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "grappled", "paralyzed",
                  "petrified", "poisoned", "prone", "restrained"],
        desc="The wailing spirit of a vain woman cursed to haunt the site of her death.",
        tags=["undead", "ghost", "dungeon", "forest", "castle"],
    ),
    "Couatl": _e(
        4, "Celestial", "Medium", "lawful good", 97, 19, 5,
        [_atk("Bite", 8, "1d6+5", "piercing")],
        special=["Poison Bite: DC 13 Con save or poisoned for 24 hours",
                 "Constrict: DC 15 Str save or grappled and restrained",
                 "Shielded Mind: immune to divination magic and reading emotions"],
        res=["radiant", "bludgeoning", "piercing", "slashing"],
        imm=["psychic", "poison"],
        desc="A feathered serpent celestial who serves law and good, often acting as a divine messenger.",
        tags=["celestial", "planar", "jungle", "divine"],
    ),
    "Ettin": _e(
        4, "Giant", "Large", "chaotic evil", 85, 12, -1,
        [_atk("Morningstar", 7, "2d8+5", "bludgeoning")],
        special=["Two Heads: advantage on Perception and saves against blindness, charm, deafness, fear, stun",
                 "Multiattack: one attack with each head's weapon"],
        desc="A two-headed giant of tremendous strength and terrible temper.",
        tags=["giant", "mountain", "dungeon", "cave"],
    ),
    "Ghost": _e(
        4, "Undead", "Medium", "any", 45, 11, 2,
        [_atk("Withering Touch", 5, "4d6", "necrotic")],
        special=["Ethereal Sight: sees into Ethereal Plane",
                 "Incorporeal: can move through objects",
                 "Possession: DC 13 Cha save or ghost possesses humanoid body",
                 "Horrifying Visage: DC 13 Wis save or frightened and aged"],
        res=["acid", "fire", "lightning", "thunder",
             "bludgeoning", "piercing", "slashing"],
        imm=["cold", "necrotic", "poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "grappled", "paralyzed",
                  "petrified", "poisoned", "prone", "restrained"],
        desc="The spirit of someone who died with powerful unresolved emotions, able to possess the living.",
        tags=["undead", "ghost", "dungeon", "castle", "tomb"],
    ),
    "Red Dragon Wyrmling": _e(
        4, "Dragon", "Medium", "chaotic evil", 75, 17, 2,
        [_atk("Bite", 6, "1d10+4", "piercing")],
        special=["Fire Breath: 15-ft cone, DC 13 Dex save or 7d6 fire"],
        imm=["fire"],
        desc="The youngest of red dragons, already arrogant and cruel, with a deadly fire breath.",
        tags=["dragon", "mountain", "dungeon", "fire"],
    ),
    "Succubus": _e(
        4, "Fiend", "Medium", "neutral evil", 66, 13, 3,
        [_atk("Claws", 5, "1d6+3", "slashing")],
        special=["Charm: DC 15 Wis save or charmed; charmed creatures can't harm the succubus",
                 "Draining Kiss: charmed target DC 15 Con save or 5d10+5 psychic",
                 "Shapechanger: can polymorph into a Small or Medium humanoid"],
        res=["cold", "fire", "lightning", "poison",
             "bludgeoning", "piercing", "slashing"],
        desc="A seductive demon from the Abyss that feeds on mortal emotions and desires.",
        tags=["fiend", "demon", "shapechanger", "planar", "urban"],
    ),
    "Wereboar": _e(
        4, "Humanoid", "Medium", "neutral evil", 78, 11, 0,
        [_atk("Tusks", 5, "2d6+3", "slashing")],
        special=["Charge: if moves 15 ft toward target, extra 2d6 slashing and DC 13 Str save or prone",
                 "Relentless: if takes 14 or fewer damage that would reduce to 0 HP, drop to 1 HP instead"],
        res=["bludgeoning", "piercing", "slashing"],
        desc="A human cursed with boar lycanthropy, recklessly charging foes.",
        tags=["humanoid", "shapechanger", "lycanthrope", "forest"],
    ),
    "Weretiger": _e(
        4, "Humanoid", "Medium", "neutral", 120, 12, 2,
        [_atk("Claws", 6, "1d8+4", "slashing")],
        special=["Shapechanger: polymorph to tiger or hybrid form",
                 "Keen Hearing and Smell: advantage on Perception",
                 "Pounce: if moves 15 ft, target DC 14 Str save or knocked prone"],
        res=["bludgeoning", "piercing", "slashing"],
        desc="A graceful lycanthrope who can shift between human and tiger form.",
        tags=["humanoid", "shapechanger", "lycanthrope", "jungle", "forest"],
    ),

    # ── CR 5 ──────────────────────────────────────────────────────────────────
    "Air Elemental": _e(
        5, "Elemental", "Large", "neutral", 90, 15, 5,
        [_atk("Slam", 8, "2d8+5", "bludgeoning")],
        special=["Whirlwind: DC 13 Str save or 3d8+5 bludgeoning and flung 20 ft",
                 "Air Form: can enter hostile space and squeeze through any opening"],
        res=["lightning", "thunder", "bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["exhaustion", "grappled", "paralyzed", "petrified", "poisoned",
                  "prone", "restrained", "unconscious"],
        desc="A living cyclone from the Elemental Plane of Air.",
        tags=["elemental", "air", "planar", "flying"],
    ),
    "Earth Elemental": _e(
        5, "Elemental", "Large", "neutral", 126, 17, -1,
        [_atk("Slam", 8, "2d8+5", "bludgeoning")],
        special=["Earth Glide: can burrow through earth/stone without disturbing it",
                 "Siege Monster: double damage against objects/structures",
                 "Multiattack: two Slam attacks"],
        res=["bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["exhaustion", "paralyzed", "petrified", "poisoned",
                  "prone", "restrained", "unconscious"],
        desc="A massive creature of living stone from the Elemental Plane of Earth.",
        tags=["elemental", "earth", "planar", "dungeon", "cave"],
    ),
    "Fire Elemental": _e(
        5, "Elemental", "Large", "neutral", 102, 13, 3,
        [_atk("Touch", 6, "2d6+3", "fire")],
        special=["Fire Form: can enter hostile space; any creature that touches it takes 1d10 fire",
                 "Illumination: sheds bright light 30 ft, dim 30 ft more",
                 "Multiattack: two Touch attacks"],
        res=["bludgeoning", "piercing", "slashing"],
        imm=["fire", "poison"],
        cond_imm=["exhaustion", "grappled", "paralyzed", "petrified", "poisoned",
                  "prone", "restrained", "unconscious"],
        desc="A roiling column of flame from the Elemental Plane of Fire.",
        tags=["elemental", "fire", "planar"],
    ),
    "Flesh Golem": _e(
        5, "Construct", "Large", "neutral", 93, 9, -1,
        [_atk("Slam", 7, "2d8+4", "bludgeoning")],
        special=["Berserk: if damaged and rolls 1 on d6, attacks random creatures until calmed",
                 "Aversion of Fire and Lightning: disadvantage on attacks in round it took fire or lightning",
                 "Multiattack: two Slam attacks"],
        imm=["lightning", "poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"],
        desc="A patchwork construct of stolen body parts animated by lightning and dark magic.",
        tags=["construct", "undead", "dungeon", "necromancy"],
    ),
    "Gladiator": _e(
        5, "Humanoid", "Medium", "any", 112, 16, 2,
        [_atk("Spear", 7, "1d6+5", "piercing")],
        special=["Multiattack: three Spear attacks or two Javelin throws",
                 "Shield Bash: +7 to hit, 2d6+5 bludgeoning and DC 15 Str save or stunned"],
        desc="A veteran arena fighter who has survived countless bouts to the death.",
        tags=["humanoid", "urban", "arena", "military"],
    ),
    "Hill Giant": _e(
        5, "Giant", "Huge", "chaotic evil", 105, 13, -1,
        [_atk("Greatclub", 8, "3d8+5", "bludgeoning")],
        special=["Multiattack: two Greatclub attacks",
                 "Rock Throw: ranged +8, 3d10+5 bludgeoning up to 60 ft"],
        desc="The dumbest and lowest of the true giants, bullying smaller creatures for food.",
        tags=["giant", "hill", "mountain", "forest"],
    ),
    "Otyugh": _e(
        5, "Aberration", "Large", "neutral", 114, 14, -1,
        [_atk("Tentacle", 6, "1d8+3", "bludgeoning")],
        special=["Multiattack: two Tentacle attacks then one Bite if grappling",
                 "Tentacle Slam: grappled target slammed; DC 14 Con save or stunned",
                 "Disease Bite: DC 15 Con save or infected with otyugh disease"],
        desc="A filth-dwelling aberration with three legs and two tentacles that lurks in sewers.",
        tags=["aberration", "dungeon", "sewer", "cave"],
    ),
    "Revenant": _e(
        5, "Undead", "Medium", "neutral", 136, 13, 0,
        [_atk("Fist", 7, "3d6+4", "bludgeoning")],
        special=["Regeneration: regains 10 HP at start of turn unless damaged by radiant or fire",
                 "Avenge: has advantage on all attacks against the creature that killed it",
                 "Undying: if destroyed, re-forms in 24 hours unless target of its vengeance is dead"],
        res=["bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "paralyzed", "poisoned", "stunned"],
        desc="An undead warrior returned from death by sheer force of will to take vengeance.",
        tags=["undead", "dungeon", "anywhere"],
    ),
    "Roper": _e(
        5, "Monstrosity", "Large", "neutral evil", 93, 20, -2,
        [_atk("Tendril", 7, "1d6+4", "bludgeoning")],
        special=["Six Tendrils: can attack six times per turn with separate tendrils",
                 "Reel: pulls restrained creature 25 ft closer",
                 "False Appearance: looks like a stalagmite"],
        desc="A ceiling-dwelling cave predator that resembles a stalagmite until it attacks.",
        tags=["monstrosity", "cave", "dungeon"],
    ),
    "Salamander": _e(
        5, "Elemental", "Large", "neutral evil", 90, 15, 1,
        [_atk("Trident", 7, "2d6+5", "piercing")],
        special=["Heated Body: touching deals 1d10 fire",
                 "Heated Weapons: melee attacks deal +3d6 fire",
                 "Multiattack: one Tail and one Trident attack"],
        res=["bludgeoning", "piercing", "slashing"],
        imm=["fire"],
        desc="A fire-serpent native to the Elemental Plane of Fire, enslaved by efreet for metalwork.",
        tags=["elemental", "fire", "planar", "dungeon"],
    ),
    "Troll": _e(
        5, "Giant", "Large", "chaotic evil", 84, 15, 2,
        [_atk("Claw", 7, "2d6+4", "slashing")],
        special=["Regeneration: regains 10 HP at start of turn unless took acid or fire last turn",
                 "Multiattack: one Bite and two Claw attacks"],
        desc="A rubbery, regenerating giant that fears only fire and acid.",
        tags=["giant", "forest", "mountain", "dungeon", "swamp"],
    ),
    "Vampire Spawn": _e(
        5, "Undead", "Medium", "neutral evil", 82, 15, 3,
        [_atk("Claws", 6, "2d4+3", "slashing")],
        special=["Regeneration: regains 10 HP at start of turn if not in sunlight/running water",
                 "Spider Climb: moves on ceilings",
                 "Bite: +6 to hit, 1d6+3 piercing and 3d6 necrotic; target's max HP reduced"],
        res=["necrotic", "bludgeoning", "piercing", "slashing"],
        desc="A vampire thrall lacking a master's full power, but lethal in the dark.",
        tags=["undead", "vampire", "dungeon", "castle", "urban"],
    ),
    "Water Elemental": _e(
        5, "Elemental", "Large", "neutral", 114, 14, 2,
        [_atk("Slam", 7, "2d8+4", "bludgeoning")],
        special=["Whelm: DC 13 Str save or grappled and can't breathe air; drowns in 3 rounds",
                 "Multiattack: two Slam attacks"],
        res=["acid", "bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["exhaustion", "grappled", "paralyzed", "petrified", "poisoned",
                  "prone", "restrained", "unconscious"],
        desc="A surging wave of living water from the Elemental Plane of Water.",
        tags=["elemental", "water", "planar", "coastal", "dungeon"],
    ),
    "Werebear": _e(
        5, "Humanoid", "Medium", "neutral good", 135, 11, 0,
        [_atk("Claws", 7, "2d8+5", "slashing")],
        special=["Shapechanger: polymorph to bear or hybrid form",
                 "Keen Smell: advantage on Perception",
                 "Multiattack: two Claw attacks"],
        res=["bludgeoning", "piercing", "slashing"],
        desc="A rare benevolent lycanthrope who shifts into bear form to protect forests.",
        tags=["humanoid", "shapechanger", "lycanthrope", "forest", "mountain"],
    ),
    "Wraith": _e(
        5, "Undead", "Medium", "neutral evil", 67, 13, 3,
        [_atk("Life Drain", 6, "4d8+3", "necrotic")],
        special=["Life Drain: target's max HP reduced by damage dealt until long rest",
                 "Create Specter: humanoid killed rises as a specter under wraith's control",
                 "Incorporeal: can move through objects"],
        res=["acid", "cold", "fire", "lightning", "thunder",
             "bludgeoning", "piercing", "slashing"],
        imm=["necrotic", "poison"],
        cond_imm=["charmed", "exhaustion", "grappled", "paralyzed", "petrified",
                  "poisoned", "prone", "restrained"],
        desc="A powerful undead spirit of hatred and malice that drains life and spawns specters.",
        tags=["undead", "dungeon", "tomb", "necromancy"],
    ),
    "Xorn": _e(
        5, "Elemental", "Medium", "neutral", 73, 19, 1,
        [_atk("Claws", 6, "1d6+4", "slashing")],
        special=["Earth Glide: moves through earth as if through air",
                 "Treasure Sense: can smell gems and precious metals within 60 ft",
                 "Multiattack: one Bite and three Claw attacks"],
        res=["piercing", "slashing"],
        desc="A three-armed earth elemental native who hunts for precious metals and gems.",
        tags=["elemental", "earth", "dungeon", "cave"],
    ),

    # ── CR 6 ──────────────────────────────────────────────────────────────────
    "Drider": _e(
        6, "Monstrosity", "Large", "chaotic evil", 123, 19, 3,
        [_atk("Longsword", 6, "1d8+4", "slashing")],
        special=["Fey Ancestry: advantage on charm saves",
                 "Spider Climb: moves on ceilings",
                 "Spellcasting: faerie fire, darkness, web, hold person",
                 "Multiattack: three attacks (Longsword or Longbow)"],
        desc="A drow cursed by Lolth into a half-drow, half-spider monstrosity.",
        tags=["monstrosity", "dungeon", "underdark", "drow"],
    ),
    "Invisible Stalker": _e(
        6, "Elemental", "Medium", "neutral", 104, 14, 6,
        [_atk("Slam", 6, "2d6+3", "bludgeoning")],
        special=["Invisibility: is invisible unless affected by magic",
                 "Faultless Tracker: given a quarry, always knows its direction"],
        res=["bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["exhaustion", "grappled", "paralyzed", "petrified", "poisoned",
                  "prone", "restrained", "unconscious"],
        desc="An invisible air elemental bound to serve as a perfect assassin and tracker.",
        tags=["elemental", "air", "planar", "assassin"],
    ),
    "Mage": _e(
        6, "Humanoid", "Medium", "any", 40, 15, 2,
        [_atk("Dagger", 6, "1d4+4", "piercing")],
        special=["Spellcasting: fireball, counterspell, lightning bolt, cone of cold, fly, greater invisibility",
                 "Arcane Ward: has 30-HP ward that absorbs damage first"],
        desc="A powerful arcane spellcaster who has studied magic for decades.",
        tags=["humanoid", "spellcaster", "urban", "dungeon"],
    ),
    "Medusa": _e(
        6, "Monstrosity", "Medium", "lawful evil", 127, 15, 2,
        [_atk("Snake Hair", 8, "1d4+5", "piercing")],
        special=["Petrifying Gaze: DC 14 Con save or restrained, then petrified on further failures",
                 "Multiattack: one Snake Hair and two Shortsword attacks"],
        desc="A once-beautiful creature cursed with snake hair and a gaze that turns flesh to stone.",
        tags=["monstrosity", "dungeon", "cave", "ruins"],
    ),
    "Wyvern": _e(
        6, "Dragon", "Large", "unaligned", 110, 13, 2,
        [_atk("Bite", 7, "2d6+4", "piercing")],
        special=["Stinger Tail: +7, 2d6+4 piercing plus DC 15 Con save or 7d6 poison",
                 "Multiattack: one Bite and one Stinger"],
        desc="A lesser dragon with a venomous tail stinger, ferocious but not intelligent.",
        tags=["dragon", "mountain", "flying", "wilderness"],
    ),
    "Young White Dragon": _e(
        6, "Dragon", "Large", "chaotic evil", 133, 17, 0,
        [_atk("Bite", 7, "2d10+4", "piercing")],
        special=["Cold Breath: 30-ft cone, DC 13 Con save or 8d8 cold",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["cold"],
        desc="The most feral of young dragons, dwelling in icy mountains and arctic wastes.",
        tags=["dragon", "arctic", "mountain", "cave"],
    ),

    # ── CR 7 ──────────────────────────────────────────────────────────────────
    "Mind Flayer": _e(
        7, "Aberration", "Medium", "lawful evil", 71, 15, 4,
        [_atk("Tentacles", 7, "2d10+4", "psychic")],
        special=["Mind Blast: 60-ft cone DC 15 Int save or 4d8+4 psychic and stunned 1 minute",
                 "Extract Brain: kills a grappled stunned creature instantly",
                 "Telepathy: communicates telepathically within 60 ft"],
        res=["psychic"],
        desc="A tentacled aberration from the Far Realm that feeds on brains and dominates minds.",
        tags=["aberration", "underdark", "dungeon", "psionic"],
    ),
    "Oni": _e(
        7, "Giant", "Large", "lawful evil", 110, 16, 2,
        [_atk("Glaive", 8, "2d10+5", "slashing")],
        special=["Shapechanger: can polymorph into Small or Medium humanoid or back",
                 "Regeneration: regains 10 HP at start of turn",
                 "Spellcasting: charm person, darkness, invisibility, sleep",
                 "Multiattack: two Glaive attacks"],
        desc="A giant devil-like creature from Eastern mythology that devours humanoids.",
        tags=["giant", "shapechanger", "mountain", "dungeon"],
    ),
    "Shield Guardian": _e(
        7, "Construct", "Large", "unaligned", 142, 17, -1,
        [_atk("Fist", 7, "2d6+4", "bludgeoning")],
        special=["Bound: linked to an amulet; wielder gains +2 AC",
                 "Shield: when wielder takes damage, guardian instead takes it (within 5 ft)",
                 "Spell Storing: can store one spell and cast it"],
        imm=["poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "paralyzed", "poisoned"],
        desc="A magical construct programmed to protect its amulet-wearing master.",
        tags=["construct", "dungeon", "castle", "guardian"],
    ),
    "Stone Giant": _e(
        7, "Giant", "Huge", "neutral", 126, 17, 2,
        [_atk("Greatclub", 9, "3d8+6", "bludgeoning")],
        special=["Stone Camouflage: advantage on Stealth in rocky terrain",
                 "Multiattack: two Greatclub attacks",
                 "Rock: ranged +9, 4d10+6 bludgeoning up to 60 ft"],
        desc="Reclusive giants who dwell in deep caves and treat their underground world as reality.",
        tags=["giant", "mountain", "cave", "dungeon"],
    ),
    "Young Black Dragon": _e(
        7, "Dragon", "Large", "chaotic evil", 127, 18, 1,
        [_atk("Bite", 7, "2d10+4", "piercing")],
        special=["Acid Breath: 30-ft line, DC 14 Dex save or 11d8 acid",
                 "Multiattack: one Bite and two Claw attacks",
                 "Amphibious: breathes air and water"],
        imm=["acid"],
        desc="A cunning young dragon that haunts swamps and ruins, driven by cruelty.",
        tags=["dragon", "swamp", "dungeon", "ruins", "acid"],
    ),
    "Young Copper Dragon": _e(
        7, "Dragon", "Large", "chaotic good", 119, 17, 1,
        [_atk("Bite", 7, "2d10+4", "piercing")],
        special=["Acid Breath: 40-ft line, DC 14 Dex save or 7d8 acid",
                 "Slowing Breath: 30-ft cone, DC 14 Con save or speed 0 for 1 minute",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["acid"],
        desc="A playful and mischievous young dragon who loves riddles and pranks.",
        tags=["dragon", "mountain", "hill", "acid"],
    ),
    "Yuan-ti Abomination": _e(
        7, "Monstrosity", "Large", "neutral evil", 127, 15, 3,
        [_atk("Bite", 8, "2d6+5", "piercing")],
        special=["Magic Resistance: advantage on saves vs spells",
                 "Constrict: +8 to hit, 2d8+5 bludgeoning and grappled",
                 "Multiattack: one Constrict and two Scimitar attacks",
                 "Spellcasting: animal friendship, suggestion, fear, polymorph"],
        imm=["poison"],
        cond_imm=["poisoned"],
        desc="The most powerful yuan-ti, more serpent than human, a favored child of Sseth.",
        tags=["monstrosity", "yuan-ti", "jungle", "dungeon", "serpent"],
    ),

    # ── CR 8 ──────────────────────────────────────────────────────────────────
    "Assassin": _e(
        8, "Humanoid", "Medium", "any non-good", 78, 15, 3,
        [_atk("Shortsword", 7, "1d6+5", "piercing")],
        special=["Sneak Attack: extra 4d6 once per turn if advantage or ally adjacent to target",
                 "Assassinate: advantage on surprised creatures; auto-critical on hit",
                 "Evasion: no damage on successful Dex save, half on failure"],
        desc="A master of stealth and poison who kills without being seen.",
        tags=["humanoid", "urban", "criminal", "assassin"],
    ),
    "Chain Devil": _e(
        8, "Fiend", "Medium", "lawful evil", 85, 16, 2,
        [_atk("Chain", 8, "2d6+4", "slashing")],
        special=["Chains: can animate up to four chains in range as bonus action",
                 "Unnerving Mask: DC 13 Wis save or frightened",
                 "Multiattack: two Chain attacks"],
        res=["cold", "bludgeoning", "piercing", "slashing"],
        imm=["fire", "poison"],
        cond_imm=["poisoned"],
        desc="A devil wrapped in animated chains that loves to bind and torment victims.",
        tags=["fiend", "devil", "planar", "dungeon"],
    ),
    "Cloaker": _e(
        8, "Aberration", "Large", "chaotic neutral", 78, 14, 2,
        [_atk("Bite", 6, "2d6+3", "piercing")],
        special=["False Appearance: resembles a black cloak on the floor",
                 "Engulf: wraps around target's head; blinded and grappled, 3d6+3 piercing per turn",
                 "Moan: DC 13 Wis save or frightened"],
        res=["bludgeoning", "piercing", "slashing"],
        desc="A ray-like aberration that disguises itself as a dark cloak before smothering prey.",
        tags=["aberration", "dungeon", "underdark"],
    ),
    "Frost Giant": _e(
        8, "Giant", "Huge", "neutral evil", 138, 15, -1,
        [_atk("Greataxe", 9, "3d12+6", "slashing")],
        special=["Multiattack: two Greataxe attacks",
                 "Rock: ranged +9, 4d10+6 bludgeoning up to 60 ft"],
        imm=["cold"],
        desc="A massive giant of the frozen north who raids villages for treasure and sport.",
        tags=["giant", "arctic", "mountain", "tundra"],
    ),
    "Gorgon": _e(
        8, "Monstrosity", "Large", "unaligned", 114, 19, 0,
        [_atk("Gore", 8, "2d12+5", "piercing")],
        special=["Petrifying Breath: 30-ft cone, DC 16 Con save or restrained then petrified",
                 "Trampling Charge: +8, target DC 16 Str save or prone",
                 "Multiattack: two attacks (Gore or Hooves)"],
        imm=["poison"],
        cond_imm=["exhaustion", "frightened", "paralyzed", "poisoned"],
        desc="An iron-plated bull-like creature whose breath turns creatures to stone.",
        tags=["monstrosity", "plains", "dungeon"],
    ),
    "Hezrou": _e(
        8, "Fiend", "Large", "chaotic evil", 136, 16, 2,
        [_atk("Bite", 7, "3d6+4", "piercing")],
        special=["Stench: DC 14 Con save or poisoned until start of next turn",
                 "Magic Resistance: advantage on saves vs spells",
                 "Multiattack: one Bite and two Claw attacks"],
        res=["cold", "fire", "lightning", "bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["poisoned"],
        desc="A frog-like demon that stinks of filth and tears at foes with its claws and teeth.",
        tags=["fiend", "demon", "planar", "dungeon"],
    ),
    "Hydra": _e(
        8, "Monstrosity", "Huge", "unaligned", 172, 15, 1,
        [_atk("Bite", 8, "1d10+5", "piercing")],
        special=["Multiple Heads: starts with 5 heads; extra Bite per head beyond one",
                 "Reactive Heads: one reaction attack per head beyond one",
                 "Wakeful: sleeps with at least one head awake",
                 "Regrow Heads: grows 2 heads per head destroyed unless fire is used"],
        desc="A multi-headed reptilian monster that grows new heads when they are cut off.",
        tags=["monstrosity", "swamp", "cave", "coastal"],
    ),
    "Night Hag": _e(
        8, "Fiend", "Medium", "neutral evil", 112, 17, 2,
        [_atk("Claws", 7, "2d8+4", "slashing")],
        special=["Nightmare Haunting: invades sleeping creature's dreams, preventing long rest",
                 "Magic Resistance: advantage on saves vs spells",
                 "Heartstone: can enter ethereal plane and move to prime material"],
        res=["cold", "fire", "bludgeoning", "piercing", "slashing"],
        desc="An ancient fiendish hag who steals into dreams and harvests evil souls.",
        tags=["fiend", "hag", "planar", "dungeon", "night"],
    ),
    "Young Bronze Dragon": _e(
        8, "Dragon", "Large", "lawful good", 142, 17, 1,
        [_atk("Bite", 8, "2d10+5", "piercing")],
        special=["Lightning Breath: 60-ft line, DC 15 Dex save or 8d10 lightning",
                 "Repulsion Breath: 30-ft cone, DC 15 Str save or pushed 40 ft",
                 "Multiattack: one Bite and two Claw attacks",
                 "Amphibious: breathes air and water"],
        imm=["lightning"],
        desc="A curious and noble young dragon drawn to places of history and conflict.",
        tags=["dragon", "coastal", "sea", "lightning"],
    ),
    "Young Green Dragon": _e(
        8, "Dragon", "Large", "lawful evil", 136, 18, 1,
        [_atk("Bite", 8, "2d10+5", "piercing")],
        special=["Poison Breath: 30-ft cone, DC 15 Con save or 12d6 poison",
                 "Multiattack: one Bite and two Claw attacks",
                 "Amphibious: breathes air and water"],
        imm=["poison"],
        desc="A manipulative young dragon who uses poison breath and deception in equal measure.",
        tags=["dragon", "forest", "poison", "dungeon"],
    ),

    # ── CR 9 ──────────────────────────────────────────────────────────────────
    "Abominable Yeti": _e(
        9, "Monstrosity", "Huge", "chaotic evil", 137, 15, 1,
        [_atk("Claw", 8, "2d6+5", "slashing")],
        special=["Chilling Gaze: DC 18 Con save or paralyzed for 1 minute",
                 "Cold Breath: 30-ft cone, DC 18 Con save or 10d8 cold",
                 "Multiattack: two Claw attacks"],
        imm=["cold"],
        desc="A gigantic, terrifying yeti of the highest peaks, whose gaze can paralyze.",
        tags=["monstrosity", "arctic", "mountain"],
    ),
    "Clay Golem": _e(
        9, "Construct", "Large", "unaligned", 133, 14, -1,
        [_atk("Slam", 8, "2d10+5", "bludgeoning")],
        special=["Acid Absorption: when hit by acid, regains HP instead",
                 "Berserk: on low HP rolls 1 on d6, attacks randomly",
                 "Haste: can self-haste once per round",
                 "Multiattack: two Slam attacks"],
        imm=["acid", "poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"],
        desc="A lumbering golem of sacred clay animated by divine magic.",
        tags=["construct", "dungeon", "divine"],
    ),
    "Cloud Giant": _e(
        9, "Giant", "Huge", "neutral good/evil", 200, 14, 3,
        [_atk("Morningstar", 12, "3d8+8", "bludgeoning")],
        special=["Keen Smell: advantage on Perception",
                 "Innate Spellcasting: detect magic, fog cloud, levitate, gaseous form, telekinesis",
                 "Multiattack: two Morningstar attacks",
                 "Rock: ranged +12, 4d10+8 bludgeoning"],
        desc="A cloud-dwelling giant of great wisdom and wealth who lives above the mundane world.",
        tags=["giant", "sky", "cloud", "flying"],
    ),
    "Fire Giant": _e(
        9, "Giant", "Huge", "lawful evil", 162, 18, -1,
        [_atk("Greatsword", 11, "6d6+7", "slashing")],
        special=["Multiattack: two Greatsword attacks",
                 "Rock: ranged +11, 4d10+7 bludgeoning"],
        imm=["fire"],
        desc="A military giant who builds volcanic fortresses and dominates fire elementals.",
        tags=["giant", "volcano", "fire", "mountain"],
    ),
    "Glabrezu": _e(
        9, "Fiend", "Large", "chaotic evil", 157, 17, 2,
        [_atk("Claw", 9, "2d8+5", "bludgeoning")],
        special=["Magic Resistance: advantage on saves vs spells",
                 "Innate Spellcasting: darkness, dispel magic, confusion, fly, power word stun",
                 "Multiattack: two Pincer and two Claw attacks"],
        res=["cold", "fire", "lightning", "bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["poisoned"],
        desc="A demon of treachery with pincers and human arms who promises wishes to corrupt mortals.",
        tags=["fiend", "demon", "planar", "dungeon"],
    ),
    "Nycaloth": _e(
        9, "Fiend", "Large", "neutral evil", 123, 18, 3,
        [_atk("Greataxe", 8, "1d12+5", "slashing")],
        special=["Magic Resistance: advantage on saves vs spells",
                 "Magic Weapons",
                 "Teleport: teleport up to 60 ft to unoccupied space",
                 "Multiattack: two Greataxe attacks"],
        res=["cold", "fire", "lightning", "bludgeoning", "piercing", "slashing"],
        imm=["acid", "poison"],
        cond_imm=["poisoned"],
        desc="A gargoyle-like yugoloth mercenary demon that serves any master for the right price.",
        tags=["fiend", "yugoloth", "planar", "dungeon"],
    ),
    "Young Blue Dragon": _e(
        9, "Dragon", "Large", "lawful evil", 152, 17, 2,
        [_atk("Bite", 9, "2d10+6", "piercing")],
        special=["Lightning Breath: 60-ft line, DC 16 Dex save or 10d10 lightning",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["lightning"],
        desc="An arrogant young dragon of the desert who considers itself a ruler over all it surveys.",
        tags=["dragon", "desert", "lightning", "dungeon"],
    ),
    "Young Silver Dragon": _e(
        9, "Dragon", "Large", "lawful good", 168, 18, 2,
        [_atk("Bite", 9, "2d10+5", "piercing")],
        special=["Cold Breath: 30-ft cone, DC 17 Con save or 9d8 cold",
                 "Paralyzing Breath: 30-ft cone, DC 17 Con save or paralyzed for 1 minute",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["cold"],
        desc="A compassionate young dragon who often takes humanoid form to walk among mortals.",
        tags=["dragon", "mountain", "arctic", "cold"],
    ),

    # ── CR 10 ─────────────────────────────────────────────────────────────────
    "Stone Golem": _e(
        10, "Construct", "Large", "unaligned", 178, 17, -1,
        [_atk("Slam", 10, "3d8+6", "bludgeoning")],
        special=["Slow: DC 17 Con save or speed halved and can only attack once",
                 "Immutable Form: immune to any spell that would alter its form",
                 "Multiattack: two Slam attacks"],
        imm=["poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"],
        desc="A colossal guardian of carved stone, impervious to most magic.",
        tags=["construct", "dungeon", "castle", "guardian"],
    ),
    "Young Red Dragon": _e(
        10, "Dragon", "Large", "chaotic evil", 178, 18, 3,
        [_atk("Bite", 10, "2d10+6", "piercing")],
        special=["Fire Breath: 30-ft cone, DC 17 Dex save or 12d6 fire",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["fire"],
        desc="The most feared of young dragons, burning everything in its path out of sheer greed.",
        tags=["dragon", "mountain", "volcano", "fire"],
    ),
    "Young Gold Dragon": _e(
        10, "Dragon", "Large", "lawful good", 178, 18, 2,
        [_atk("Bite", 10, "2d10+6", "piercing")],
        special=["Fire Breath: 30-ft cone, DC 17 Dex save or 10d10 fire",
                 "Weakening Breath: 30-ft cone, DC 17 Str save or disadvantage on Str attacks for 1 minute",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["fire"],
        desc="One of the most noble of young dragons, dedicated to protecting the innocent.",
        tags=["dragon", "plains", "hill", "fire"],
    ),

    # ── CR 11 ─────────────────────────────────────────────────────────────────
    "Aboleth": _e(
        10, "Aberration", "Large", "lawful evil", 135, 17, 2,
        [_atk("Tentacle", 9, "2d6+5", "bludgeoning")],
        special=["Mucous Cloud: water-breathing creatures near it must DC 14 Con save or can only breathe water",
                 "Probe Mind: DC 14 Wis save or aboleth reads thoughts and learns secrets",
                 "Enslave: DC 14 Wis save or charmed for 30 days",
                 "Multiattack: three Tentacle attacks"],
        res=["bludgeoning", "piercing", "slashing"],
        desc="An ancient alien intelligence that predates the gods, lurking in deep lakes.",
        tags=["aberration", "water", "dungeon", "underdark", "psionic"],
    ),
    "Behir": _e(
        11, "Monstrosity", "Huge", "neutral evil", 168, 17, 3,
        [_atk("Bite", 10, "3d10+6", "piercing")],
        special=["Lightning Breath: 20-ft line, DC 16 Dex save or 7d10 lightning",
                 "Constrict: DC 16 Str save or grappled and restrained, 2d10+6 bludgeoning",
                 "Swallow: swallowed target is blinded, restrained, 6d6 acid per turn"],
        imm=["lightning"],
        desc="A twelve-legged serpentine predator with lightning breath that hates dragons.",
        tags=["monstrosity", "mountain", "dungeon", "cave"],
    ),
    "Djinni": _e(
        11, "Elemental", "Large", "chaotic good", 161, 17, 5,
        [_atk("Scimitar", 9, "2d6+5", "slashing")],
        special=["Elemental Demise: on death, explosion DC 14 Dex save or 3d6 thunder",
                 "Innate Spellcasting: detect evil and good, detect magic, thunderwave, wind walk, conjure elemental",
                 "Multiattack: three Scimitar attacks"],
        imm=["lightning", "thunder"],
        desc="A noble genie of elemental air bound by duty or magic to grant limited wishes.",
        tags=["elemental", "air", "planar", "flying"],
    ),
    "Efreeti": _e(
        11, "Elemental", "Large", "lawful evil", 200, 17, 3,
        [_atk("Scimitar", 10, "2d6+6", "slashing")],
        special=["Innate Spellcasting: detect magic, enlarge/reduce, tongues, conjure elemental, gaseous form, wish (3/day)",
                 "Multiattack: two Scimitar attacks"],
        imm=["fire"],
        desc="A tyrannical genie of elemental fire who enslaves creatures and grants dark wishes.",
        tags=["elemental", "fire", "planar"],
    ),
    "Horned Devil": _e(
        11, "Fiend", "Large", "lawful evil", 178, 18, 3,
        [_atk("Fork", 10, "2d8+6", "piercing")],
        special=["Magic Resistance: advantage on saves vs spells",
                 "Magic Weapons",
                 "Multiattack: two Fork attacks and one Tail attack",
                 "Tail: +10, 1d8+6 piercing and DC 17 Con save or poisoned for 1 minute"],
        res=["cold", "bludgeoning", "piercing", "slashing"],
        imm=["fire", "poison"],
        cond_imm=["poisoned"],
        desc="A winged devil of immense power who commands lesser fiends in the Nine Hells.",
        tags=["fiend", "devil", "planar", "flying"],
    ),
    "Roc": _e(
        11, "Beast", "Gargantuan", "unaligned", 248, 15, 3,
        [_atk("Beak", 13, "4d8+9", "piercing")],
        special=["Keen Sight: advantage on Perception",
                 "Multiattack: one Beak and one Talons attack",
                 "Talons: +13, 4d6+9 slashing and target grappled; DC 19 Str to escape"],
        desc="An enormous eagle large enough to carry an elephant, nesting on mountain peaks.",
        tags=["beast", "mountain", "flying", "coastal"],
    ),

    # ── CR 12 ─────────────────────────────────────────────────────────────────
    "Archmage": _e(
        12, "Humanoid", "Medium", "any", 99, 12, 2,
        [_atk("Dagger", 6, "1d4+2", "piercing")],
        special=["Spellcasting: time stop, wish, meteor swarm, mind blank, power word kill",
                 "Magic Resistance: advantage on saves vs spells",
                 "Spell Mastery: can cast lower-level spells without slots"],
        desc="The most powerful of mortal wizards, capable of reshaping reality with a word.",
        tags=["humanoid", "spellcaster", "urban", "dungeon", "tower"],
    ),
    "Erinyes": _e(
        12, "Fiend", "Medium", "lawful evil", 153, 18, 7,
        [_atk("Longsword", 9, "1d8+6", "slashing")],
        special=["Hellish Weapons: attacks deal extra 3d8 poison",
                 "Magic Resistance: advantage on saves vs spells",
                 "Magic Weapons",
                 "Multiattack: three Longsword or Longbow attacks"],
        res=["cold", "bludgeoning", "piercing", "slashing"],
        imm=["fire", "poison"],
        cond_imm=["poisoned"],
        desc="A fallen angel of law, mercilessly pursuing those who break divine covenants.",
        tags=["fiend", "devil", "planar", "flying"],
    ),
    "Gynosphinx": _e(
        11, "Monstrosity", "Large", "lawful neutral", 136, 17, 2,
        [_atk("Claws", 9, "2d8+6", "slashing")],
        special=["Inscrutable: immune to divination and to having emotions sensed",
                 "Magic Weapons",
                 "Spellcasting: detect magic, identify, legend lore, locate object, dispel magic",
                 "Multiattack: two Claw attacks"],
        imm=["psychic"],
        cond_imm=["charmed", "frightened"],
        desc="A winged lion with a woman's face who guards ancient secrets and poses riddles.",
        tags=["monstrosity", "sphinx", "desert", "dungeon", "ruins"],
    ),
    "Nalfeshnee": _e(
        13, "Fiend", "Large", "chaotic evil", 184, 18, 2,
        [_atk("Bite", 7, "2d8+3", "piercing")],
        special=["Magic Resistance: advantage on saves vs spells",
                 "Horrific Nimbus: spectral wings shed holy light that blinds",
                 "Multiattack: one Bite and two Claw attacks"],
        res=["cold", "fire", "lightning", "bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["poisoned"],
        desc="A grossly fat ape-like demon that rules through terror and brute force.",
        tags=["fiend", "demon", "planar", "dungeon"],
    ),

    # ── CR 13 ─────────────────────────────────────────────────────────────────
    "Adult White Dragon": _e(
        13, "Dragon", "Huge", "chaotic evil", 200, 18, 0,
        [_atk("Bite", 10, "2d10+6", "piercing")],
        special=["Cold Breath: 60-ft cone, DC 19 Con save or 12d8 cold",
                 "Legendary Resistance: 3/day can auto-succeed on a failed save",
                 "Multiattack: one Bite and two Claw attacks",
                 "Frightful Presence: DC 16 Wis save or frightened"],
        imm=["cold"],
        desc="The most feral and primitive of adult dragons, ruled by hunger and instinct.",
        tags=["dragon", "arctic", "mountain", "cold", "legendary"],
    ),
    "Storm Giant": _e(
        13, "Giant", "Huge", "chaotic good", 230, 16, 2,
        [_atk("Greatsword", 14, "6d6+9", "slashing")],
        special=["Amphibious: breathes air and water",
                 "Innate Spellcasting: detect magic, feather fall, levitate, control weather, water breathing",
                 "Lightning Strike: 3/day, +14, 6d6+9 lightning",
                 "Multiattack: two Greatsword attacks"],
        imm=["cold", "lightning", "thunder"],
        desc="The mightiest of true giants, dwelling in seas and storm clouds, touched by prophecy.",
        tags=["giant", "storm", "coastal", "sea", "mountain"],
    ),
    "Ultroloth": _e(
        13, "Fiend", "Medium", "neutral evil", 153, 19, 5,
        [_atk("Longsword", 12, "1d8+7", "slashing")],
        special=["Magic Resistance: advantage on saves vs spells",
                 "Magic Weapons",
                 "Innate Spellcasting: alter self, charm person, detect thoughts, hypnotic pattern, dimension door",
                 "Multiattack: two Longsword attacks"],
        res=["cold", "fire", "lightning", "bludgeoning", "piercing", "slashing"],
        imm=["acid", "poison"],
        cond_imm=["charmed", "frightened", "poisoned"],
        desc="The highest rank of yugoloth mercenary, a featureless-faced manipulator.",
        tags=["fiend", "yugoloth", "planar", "dungeon"],
    ),
    "Vampire": _e(
        13, "Undead", "Medium", "lawful evil", 144, 16, 4,
        [_atk("Claws", 9, "2d8+6", "slashing")],
        special=["Legendary Resistance: 3/day",
                 "Charm: DC 17 Wis save or charmed and regards vampire as trusted friend",
                 "Regeneration: regains 20 HP at start of turn if not in sunlight/running water",
                 "Children of the Night: can call rats/bats/wolves",
                 "Bite: DC 17 Con save or 3d6 necrotic; max HP reduced"],
        res=["necrotic", "bludgeoning", "piercing", "slashing"],
        desc="An immortal undead predator of the night who dominates mortal minds.",
        tags=["undead", "vampire", "castle", "dungeon", "urban", "legendary"],
    ),

    # ── CR 14 ─────────────────────────────────────────────────────────────────
    "Adult Black Dragon": _e(
        14, "Dragon", "Huge", "chaotic evil", 195, 19, 2,
        [_atk("Bite", 11, "2d10+7", "piercing")],
        special=["Acid Breath: 60-ft line, DC 18 Dex save or 12d8 acid",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 16 Wis save or frightened",
                 "Multiattack: one Bite and two Claw attacks",
                 "Amphibious"],
        imm=["acid"],
        desc="A corrupt adult dragon that haunts swamps and ruins, obsessed with death and treasure.",
        tags=["dragon", "swamp", "dungeon", "ruins", "acid", "legendary"],
    ),
    "Adult Copper Dragon": _e(
        14, "Dragon", "Huge", "chaotic good", 184, 18, 1,
        [_atk("Bite", 10, "2d10+6", "piercing")],
        special=["Acid Breath: 60-ft line, DC 18 Dex save or 9d8 acid",
                 "Slowing Breath: 60-ft cone, DC 18 Con save or speed 0 for 1 minute",
                 "Legendary Resistance: 3/day",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["acid"],
        desc="A witty, trickster adult dragon who collects jokes and riddles as eagerly as gold.",
        tags=["dragon", "mountain", "hill", "acid", "legendary"],
    ),

    # ── CR 15 ─────────────────────────────────────────────────────────────────
    "Adult Bronze Dragon": _e(
        15, "Dragon", "Huge", "lawful good", 212, 19, 2,
        [_atk("Bite", 11, "2d10+7", "piercing")],
        special=["Lightning Breath: 90-ft line, DC 19 Dex save or 12d10 lightning",
                 "Repulsion Breath: 60-ft cone, DC 19 Str save or pushed 60 ft",
                 "Legendary Resistance: 3/day",
                 "Multiattack: one Bite and two Claw attacks",
                 "Amphibious"],
        imm=["lightning"],
        desc="A proud adult dragon who reveres military history and fights evil with martial fervor.",
        tags=["dragon", "coastal", "sea", "lightning", "legendary"],
    ),
    "Adult Green Dragon": _e(
        15, "Dragon", "Huge", "lawful evil", 207, 19, 1,
        [_atk("Bite", 11, "2d10+7", "piercing")],
        special=["Poison Breath: 60-ft cone, DC 18 Con save or 16d6 poison",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 17 Wis save or frightened",
                 "Multiattack: one Bite and two Claw attacks",
                 "Amphibious"],
        imm=["poison"],
        desc="The most cunning of adult dragons, weaving webs of deception across entire kingdoms.",
        tags=["dragon", "forest", "dungeon", "poison", "legendary"],
    ),
    "Purple Worm": _e(
        15, "Monstrosity", "Gargantuan", "unaligned", 247, 18, -2,
        [_atk("Bite", 14, "3d8+9", "piercing")],
        special=["Tunneler: can burrow through solid rock",
                 "Tail Stinger: +11, 2d6+9 piercing and DC 19 Con save or 12d6 poison",
                 "Swallow: swallowed target is blinded and restrained, 6d6 acid per turn",
                 "Multiattack: one Bite and one Tail Stinger"],
        desc="A city-block-sized worm that burrows through solid rock swallowing prey whole.",
        tags=["monstrosity", "dungeon", "underdark", "cave"],
    ),

    # ── CR 16 ─────────────────────────────────────────────────────────────────
    "Adult Blue Dragon": _e(
        16, "Dragon", "Huge", "lawful evil", 225, 19, 2,
        [_atk("Bite", 12, "2d10+8", "piercing")],
        special=["Lightning Breath: 90-ft line, DC 19 Dex save or 13d10 lightning",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 18 Wis save or frightened",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["lightning"],
        desc="The most vain of adult dragons, who craves power over other creatures and rules by fear.",
        tags=["dragon", "desert", "lightning", "dungeon", "legendary"],
    ),
    "Adult Silver Dragon": _e(
        16, "Dragon", "Huge", "lawful good", 243, 19, 2,
        [_atk("Bite", 11, "2d10+7", "piercing")],
        special=["Cold Breath: 60-ft cone, DC 20 Con save or 12d8 cold",
                 "Paralyzing Breath: 60-ft cone, DC 20 Con save or paralyzed for 1 minute",
                 "Legendary Resistance: 3/day",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["cold"],
        desc="A magnificent adult dragon who often takes humanoid form to live among mortals.",
        tags=["dragon", "mountain", "arctic", "cold", "legendary"],
    ),
    "Iron Golem": _e(
        16, "Construct", "Large", "unaligned", 210, 20, -1,
        [_atk("Slam", 13, "3d10+7", "bludgeoning")],
        special=["Fire Absorption: fire damage heals it instead",
                 "Magic Resistance: advantage on saves vs spells",
                 "Poison Breath: 15-ft cone, DC 19 Con save or 10d8 poison",
                 "Multiattack: two Slam attacks"],
        imm=["fire", "poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "paralyzed", "petrified", "poisoned"],
        desc="The mightiest of golems, forged from enchanted iron to protect wizard towers.",
        tags=["construct", "dungeon", "castle", "guardian"],
    ),
    "Marilith": _e(
        16, "Fiend", "Large", "chaotic evil", 189, 18, 5,
        [_atk("Longsword", 9, "2d8+5", "slashing")],
        special=["Magic Resistance: advantage on saves vs spells",
                 "Magic Weapons",
                 "Reactive: six reactions per round for one Longsword attack each",
                 "Multiattack: up to six Longsword attacks"],
        res=["cold", "fire", "lightning", "bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["poisoned"],
        desc="A six-armed snake-bodied demon of terrifying martial skill.",
        tags=["fiend", "demon", "planar", "dungeon"],
    ),

    # ── CR 17 ─────────────────────────────────────────────────────────────────
    "Adult Gold Dragon": _e(
        17, "Dragon", "Huge", "lawful good", 256, 19, 2,
        [_atk("Bite", 13, "2d10+8", "piercing")],
        special=["Fire Breath: 60-ft cone, DC 21 Dex save or 13d10 fire",
                 "Weakening Breath: 60-ft cone, DC 21 Str save or disadvantage on Str attacks",
                 "Legendary Resistance: 3/day",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["fire"],
        desc="The most regal and wise of adult dragons, a champion of law and goodness.",
        tags=["dragon", "plains", "hill", "fire", "legendary"],
    ),
    "Adult Red Dragon": _e(
        17, "Dragon", "Huge", "chaotic evil", 256, 19, 3,
        [_atk("Bite", 14, "2d10+9", "piercing")],
        special=["Fire Breath: 60-ft cone, DC 21 Dex save or 18d6 fire",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 19 Wis save or frightened",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["fire"],
        desc="The most covetous and terrible of adult dragons, whose rage can level cities.",
        tags=["dragon", "mountain", "volcano", "fire", "legendary"],
    ),
    "Androsphinx": _e(
        17, "Monstrosity", "Large", "lawful neutral", 199, 17, 0,
        [_atk("Claw", 12, "2d10+6", "slashing")],
        special=["Inscrutable: immune to divination and sensing emotions",
                 "Roar: DC 18 Wis save or frightened; second failure stunned; third petrified",
                 "Spellcasting: divine word, holy aura, plane shift, flame strike",
                 "Legendary Resistance: 3/day",
                 "Multiattack: two Claw attacks"],
        imm=["psychic"],
        cond_imm=["charmed", "frightened"],
        desc="A male sphinx who guards sacred places, dispensing curses or wisdom at his pleasure.",
        tags=["monstrosity", "sphinx", "desert", "dungeon", "ruins", "legendary"],
    ),
    "Death Knight": _e(
        17, "Undead", "Medium", "chaotic evil", 180, 20, 0,
        [_atk("Longsword", 11, "1d8+5", "slashing")],
        special=["Legendary Resistance: 3/day",
                 "Marshal Undead: undead creatures within 60 ft have advantage on saves",
                 "Spellcasting: wall of ice, hold monster, finger of death",
                 "Hellfire Orb: 20-ft radius DC 18 Dex save or 10d10 fire plus 10d10 necrotic",
                 "Multiattack: three Longsword attacks"],
        imm=["necrotic", "poison"],
        cond_imm=["exhaustion", "frightened", "poisoned"],
        desc="A fallen paladin raised as a lich-like undead champion, condemned to serve darkness.",
        tags=["undead", "dungeon", "castle", "legendary", "necromancy"],
    ),
    "Dragon Turtle": _e(
        17, "Dragon", "Gargantuan", "neutral", 341, 20, -1,
        [_atk("Bite", 13, "3d12+7", "piercing")],
        special=["Steam Breath: 60-ft cone, DC 18 Con save or 15d6 fire",
                 "Multiattack: one Bite and two Claw attacks",
                 "Amphibious"],
        res=["fire"],
        desc="An ancient reptilian leviathan whose shell can be mistaken for a small island.",
        tags=["dragon", "sea", "coastal", "water"],
    ),

    # ── CR 19 ─────────────────────────────────────────────────────────────────
    "Balor": _e(
        19, "Fiend", "Huge", "chaotic evil", 262, 19, 4,
        [_atk("Longsword", 14, "3d8+8", "slashing")],
        special=["Legendary Resistance: 3/day (in some campaigns)",
                 "Fire Aura: 5-ft aura deals 3d6 fire at start of each creature's turn",
                 "Magic Resistance: advantage on saves vs spells",
                 "Death Throes: explodes on death, DC 20 Dex save or 20d6 fire",
                 "Multiattack: one Longsword and one Whip attack"],
        res=["cold", "lightning", "bludgeoning", "piercing", "slashing"],
        imm=["fire", "poison"],
        cond_imm=["poisoned"],
        desc="A lord of the Abyss, a towering demon of fire and darkness who leads demonic armies.",
        tags=["fiend", "demon", "planar", "legendary"],
    ),

    # ── CR 20 ─────────────────────────────────────────────────────────────────
    "Ancient White Dragon": _e(
        20, "Dragon", "Gargantuan", "chaotic evil", 333, 20, 0,
        [_atk("Bite", 13, "2d10+8", "piercing")],
        special=["Cold Breath: 90-ft cone, DC 22 Con save or 16d8 cold",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 17 Wis save or frightened",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["cold"],
        desc="The oldest and most savage of white dragons, a force of icy destruction.",
        tags=["dragon", "arctic", "mountain", "cold", "legendary"],
    ),
    "Ancient Brass Dragon": _e(
        20, "Dragon", "Gargantuan", "chaotic good", 297, 20, 1,
        [_atk("Bite", 14, "2d10+9", "piercing")],
        special=["Fire Breath: 90-ft line, DC 21 Dex save or 14d6 fire",
                 "Sleep Breath: 90-ft cone, DC 21 Con save or fall unconscious for 10 minutes",
                 "Legendary Resistance: 3/day",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["fire"],
        desc="The most talkative of ancient dragons, who will spin tales for hours — then kill you.",
        tags=["dragon", "desert", "fire", "legendary"],
    ),
    "Pit Fiend": _e(
        20, "Fiend", "Large", "lawful evil", 300, 19, 3,
        [_atk("Bite", 14, "4d6+9", "piercing")],
        special=["Fear Aura: DC 21 Wis save or frightened while in 20 ft",
                 "Magic Resistance: advantage on saves vs spells",
                 "Magic Weapons",
                 "Innate Spellcasting: detect magic, fireball, hold monster, wall of fire",
                 "Multiattack: one Bite and two Fork attacks and one Tail attack"],
        res=["cold", "bludgeoning", "piercing", "slashing"],
        imm=["fire", "poison"],
        cond_imm=["poisoned"],
        desc="One of the most powerful devils, a general of Hell's legions answerable only to archdevils.",
        tags=["fiend", "devil", "planar", "legendary"],
    ),

    # ── CR 21 ─────────────────────────────────────────────────────────────────
    "Ancient Black Dragon": _e(
        21, "Dragon", "Gargantuan", "chaotic evil", 367, 22, 3,
        [_atk("Bite", 14, "2d10+9", "piercing")],
        special=["Acid Breath: 90-ft line, DC 22 Dex save or 15d8 acid",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 19 Wis save or frightened",
                 "Amphibious",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["acid"],
        desc="An ancient dragon of rot and ruin who has watched civilizations rise and crumble.",
        tags=["dragon", "swamp", "dungeon", "ruins", "acid", "legendary"],
    ),
    "Ancient Copper Dragon": _e(
        21, "Dragon", "Gargantuan", "chaotic good", 350, 21, 1,
        [_atk("Bite", 15, "2d10+9", "piercing")],
        special=["Acid Breath: 90-ft line, DC 23 Dex save or 12d8 acid",
                 "Slowing Breath: 90-ft cone, DC 23 Con save or speed 0 for 1 minute",
                 "Legendary Resistance: 3/day",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["acid"],
        desc="The oldest trickster dragon, who has run long cons and ridiculous schemes for millennia.",
        tags=["dragon", "mountain", "hill", "acid", "legendary"],
    ),
    "Lich": _e(
        21, "Undead", "Medium", "any evil", 135, 17, 3,
        [_atk("Paralyzing Touch", 12, "3d6", "cold")],
        special=["Legendary Resistance: 3/day",
                 "Rejuvenation: destroyed lich returns in 1d10 days if phylactery intact",
                 "Turn Resistance: advantage on saves against turn undead",
                 "Spellcasting: power word kill, finger of death, disintegrate, time stop, wish",
                 "Corruption Orb: +12, 10d8 necrotic, target's max HP reduced"],
        res=["cold", "lightning", "necrotic", "bludgeoning", "piercing", "slashing"],
        imm=["poison"],
        cond_imm=["charmed", "exhaustion", "frightened", "paralyzed", "poisoned"],
        desc="A wizard who voluntarily became an undead horror to achieve immortality.",
        tags=["undead", "dungeon", "tower", "legendary", "spellcaster"],
    ),

    # ── CR 22 ─────────────────────────────────────────────────────────────────
    "Ancient Bronze Dragon": _e(
        22, "Dragon", "Gargantuan", "lawful good", 367, 22, 2,
        [_atk("Bite", 15, "2d10+10", "piercing")],
        special=["Lightning Breath: 120-ft line, DC 23 Dex save or 16d10 lightning",
                 "Repulsion Breath: 90-ft cone, DC 23 Str save or pushed 90 ft",
                 "Legendary Resistance: 3/day",
                 "Amphibious",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["lightning"],
        desc="An ancient dragon who has witnessed wars and revolutions, a living record of history.",
        tags=["dragon", "coastal", "sea", "lightning", "legendary"],
    ),
    "Ancient Green Dragon": _e(
        22, "Dragon", "Gargantuan", "lawful evil", 385, 21, 1,
        [_atk("Bite", 15, "2d10+9", "piercing")],
        special=["Poison Breath: 90-ft cone, DC 22 Con save or 22d6 poison",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 21 Wis save or frightened",
                 "Amphibious",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["poison"],
        desc="The spider at the center of an ancient web of political manipulation and dark secrets.",
        tags=["dragon", "forest", "dungeon", "poison", "legendary"],
    ),

    # ── CR 23 ─────────────────────────────────────────────────────────────────
    "Ancient Blue Dragon": _e(
        23, "Dragon", "Gargantuan", "lawful evil", 481, 22, 3,
        [_atk("Bite", 16, "2d10+10", "piercing")],
        special=["Lightning Breath: 120-ft line, DC 23 Dex save or 16d10 lightning",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 21 Wis save or frightened",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["lightning"],
        desc="An ancient tyrant who commands storms and rules vast desert empires through terror.",
        tags=["dragon", "desert", "lightning", "legendary"],
    ),
    "Ancient Silver Dragon": _e(
        23, "Dragon", "Gargantuan", "lawful good", 487, 22, 2,
        [_atk("Bite", 15, "2d10+9", "piercing")],
        special=["Cold Breath: 90-ft cone, DC 24 Con save or 16d8 cold",
                 "Paralyzing Breath: 90-ft cone, DC 24 Con save or paralyzed 1 minute",
                 "Legendary Resistance: 3/day",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["cold"],
        desc="The eldest of silver dragons, who has spent centuries among mortals fighting injustice.",
        tags=["dragon", "mountain", "arctic", "cold", "legendary"],
    ),

    # ── CR 24 ─────────────────────────────────────────────────────────────────
    "Ancient Gold Dragon": _e(
        24, "Dragon", "Gargantuan", "lawful good", 546, 22, 3,
        [_atk("Bite", 17, "2d10+11", "piercing")],
        special=["Fire Breath: 90-ft cone, DC 24 Dex save or 13d10 fire",
                 "Weakening Breath: 90-ft cone, DC 24 Str save or disadvantage on Str attacks",
                 "Legendary Resistance: 3/day",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["fire"],
        desc="The pinnacle of dragonkind, a philosopher-king who has shaped the fates of nations.",
        tags=["dragon", "plains", "hill", "fire", "legendary"],
    ),
    "Ancient Red Dragon": _e(
        24, "Dragon", "Gargantuan", "chaotic evil", 546, 22, 3,
        [_atk("Bite", 17, "2d10+11", "piercing")],
        special=["Fire Breath: 90-ft cone, DC 24 Dex save or 26d6 fire",
                 "Legendary Resistance: 3/day",
                 "Frightful Presence: DC 21 Wis save or frightened",
                 "Multiattack: one Bite and two Claw attacks"],
        imm=["fire"],
        desc="The most powerful and terrifying dragon alive, a catastrophe in the shape of a lizard.",
        tags=["dragon", "mountain", "volcano", "fire", "legendary"],
    ),

    # ── CR 30 ─────────────────────────────────────────────────────────────────
    "Tarrasque": _e(
        30, "Monstrosity", "Gargantuan", "unaligned", 676, 25, 0,
        [_atk("Bite", 19, "4d12+10", "piercing")],
        special=["Legendary Resistance: 3/day",
                 "Siege Monster: double damage vs objects/structures",
                 "Magic Resistance: advantage on saves vs spells",
                 "Reflective Carapace: spells bounce off on 1-5 on d6",
                 "Frightful Presence: DC 27 Wis save or frightened",
                 "Multiattack: one Bite, two Claws, one Horn, one Tail"],
        res=["bludgeoning", "piercing", "slashing"],
        cond_imm=["charmed", "frightened", "paralyzed", "poisoned"],
        desc="The most destructive creature in existence. When it wakes, kingdoms fall.",
        tags=["monstrosity", "legendary", "catastrophe"],
    ),
}


# ── Helper functions ───────────────────────────────────────────────────────────

def by_cr(cr):
    return {name: e for name, e in ENEMIES.items() if e["cr"] == cr}


def by_cr_range(min_cr, max_cr):
    return {name: e for name, e in ENEMIES.items() if min_cr <= e["cr"] <= max_cr}


def appropriate_for_level(player_level):
    min_cr = max(0, player_level * 0.25 - 0.5)
    max_cr = player_level * 1.5
    return by_cr_range(min_cr, max_cr)


def enemy_list_for_dm(player_level=None):
    if player_level is not None:
        pool = appropriate_for_level(player_level)
        if not pool:
            pool = ENEMIES
    else:
        pool = ENEMIES

    tiers = [
        ("Trivial (CR 0–1)",   0,    1),
        ("Low (CR 2–4)",       2,    4),
        ("Medium (CR 5–8)",    5,    8),
        ("High (CR 9–16)",     9,   16),
        ("Boss (CR 17–24)",   17,   24),
        ("Legendary (CR 25+)",25,   30),
    ]

    lines = ["AVAILABLE ENEMIES — use exact names in [COMBAT:] tags:"]
    for label, lo, hi in tiers:
        names = sorted(
            name for name, e in pool.items() if lo <= e["cr"] <= hi
        )
        if names:
            lines.append(f"  {label}: {', '.join(names)}")
    return "\n".join(lines)
